
isom <- 
  isom  %>% 
  arrange(cab_id, t_date, t_dplus) %>% 
  group_by(cab_id)  %>% 
  summarise(
    cab_pm                 = first(cab_pm                 ) ,
    cab_in                 = first(cab_in                 ) ,
    cab_out                = first(cab_out                ) ,
    cab_comp               = first(cab_comp               ) ,
    new_gov                = first(new_gov                ) ,
    next_elect             = first(next_elect             ) ,
    max_cab_dur            = first(max_cab_dur            ) ,
    abs_no_party           = first(abs_no_party           ) ,
    abs_no_party_seat      = first(abs_no_party_seat      ) ,
    abs_no_party_seat_plus = first(abs_no_party_seat_plus ) ,
    eff_no_party           = first(eff_no_party           ) ,
    barg_pow               = first(barg_pow               ) ,
    eff_no_upper           = first(eff_no_upper           ) ,
    largest_seat           = first(largest_seat           ) ,
    barg_pow_largest       = first(barg_pow_largest       ) ,
    min_sit                = first(min_sit                ) ,
    non_part_cab           = first(non_part_cab           ) ,
    coal_cab               = first(coal_cab               ) ,
    cab_seats              = first(cab_seats              ) ,
    cab_share              = first(cab_share              ) ,
    cab_seats_upp          = first(cab_seats_upp          ) ,
    no_cab_parties         = first(no_cab_parties         ) ,
    change_cab_parties     = first(change_cab_parties     ) ,
    single_maj_cab         = first(single_maj_cab         ) ,
    single_min_cab         = first(single_min_cab         ) ,
    coal_min_cab           = first(coal_min_cab           ) ,
    maj_cab                = first(maj_cab                ) ,
    maj_coal               = first(maj_coal               ) ,
    mwc_cab                = first(mwc_cab                ) ,
    smc_cab                = first(smc_cab                ) ,
    gov_type               = first(gov_type               ) ,
    cab_n_members          = first(cab_n_members          ) ,
    cab_n_members_change   = first(cab_n_members_change   ) ,
    parl_pref              = first(parl_pref              ) ,
    polariz                = first(polariz                ) ,
    cab_pref               = first(cab_pref               ) ,
    connect_cab            = first(connect_cab            ) ,
    mwc_connected_cab      = first(mwc_connected_cab      ) ,
    low_leg                = first(low_leg                ) ,
    const_amend_supermaj   = first(const_amend_supermaj   ) ,
    strong_low             = first(strong_low             ) ,
    weak_low               = first(weak_low               ) ,
    bicamer                = first(bicamer                ) ,
    pos_parl               = first(pos_parl               ) ,
    no_confid_absmaj       = first(no_confid_absmaj       ) ,
    no_confid_construct    = first(no_confid_construct    ) ,
    cab_unanimity          = first(cab_unanimity          ) ,
    cab_pm_cons            = first(cab_pm_cons            ) ,
    cab_leg                = first(cab_leg                ) ,
    semi_pres              = first(semi_pres              ) ,
    seats_low              = first(seats_low              ) ,
    seats_upp              = first(seats_upp              ) ,
    cab_dur_100            = first(cab_dur_100            ) ,
    cab_dur_rel            = first(cab_dur_rel            ) ,
    cab_dur_abs1           = first(cab_dur_abs1           ) ,
    cab_dur_abs2           = first(cab_dur_abs2           ) ,
    el_volat_cab           = first(el_volat_cab           ) ,
    el_volat_ave           = first(el_volat_ave           ) ,
    el_perf_cab            = first(el_perf_cab            ) ,
    country_id             = first(country_id             ) ,
    policy_conf            = first(policy_conf            ) ,
    policy_conf_ch         = first(policy_conf_ch         ) ,
    cab_pref_ch            = first(cab_pref_ch            ) ,
    maj_min                = first(maj_min          ),
    min_maj                = first(min_maj          ),
    opm_coal               = first(opm_coal         ),
    coal_opm               = first(coal_opm         ),
    erd_pg_mp_matcher      = first(erd_pg_mp_matcher),
    cab_id_pg              = first(cab_id_pg        ),
    cab_id_prev_pg         = first(cab_id_prev_pg   ),
    cab_name_pg            = first(cab_name_pg      ),
    cab_start_pg           = first(cab_start_pg     ),
    el_date_pg             = first(el_date_pg       ),
    el_first_pg            = first(el_first_pg      ),
    el_id_pg               = first(el_id_pg         ),
    idl                    = first(idl              ),
    idl_dist_gop           = first(idl_dist_gop     ),
    idl_pnt_all            = first(idl_pnt_all      ),
    idl_pnt_gov            = first(idl_pnt_gov      ),
    idl_pnt_opp            = first(idl_pnt_opp      ),
    idl_pol_all            = first(idl_pol_all      ),
    idl_pol_gov            = first(idl_pol_gov      ),
    idl_pol_opp            = first(idl_pol_opp      ),
    idl_rng_all            = first(idl_rng_all      ),
    idl_rng_gov            = first(idl_rng_gov      ),
    idl_rng_opp            = first(idl_rng_opp      ),
    n_parties              = first(n_parties        ),
    seats_gov              = first(seats_gov        ),
    seats_opp              = first(seats_opp        ),
    sts_tot_pg             = first(sts_tot_pg       ),
    volatility             = first(volatility       ),
    
    n_reforms              = n(), 
    t_id_fst               = first(t_id             ),
    t_id_lst               = last(t_id              ),
    country                = first(country          ),
    ctr                    = first(ctr              ),
    erd_cab_id             = first(erd_cab_id       ),
    
    t_country              = first(t_country ),
    t_date_fst             = first(t_date    ),
    t_dplus_fst            = first(t_dplus   ),
    t_daccept_fst          = first(t_daccept ),
    t_dpromul_fst          = first(t_dpromul ),
    t_denact_fst           = first(t_denact  ),
    t_date_lst             = last(t_date    ),
    t_dplus_lst            = last(t_dplus   ),
    t_daccept_lst          = last(t_daccept ),
    t_dpromul_lst          = last(t_dpromul ),
    t_denact_lst           = last(t_denact  ),
    db_version             = first(db_version),
    db_lastupdate          = first(db_lastupdate),
    
    lns_all_mn                = mean(lns_all        ,na.rm=TRUE),
    wds_raw_all_mn            = mean(wds_raw_all    ,na.rm=TRUE),
    wds_clean_all_mn          = mean(wds_clean_all  ,na.rm=TRUE),
    lns_rel_mn                = mean(lns_rel        ,na.rm=TRUE),
    wds_raw_rel_mn            = mean(wds_raw_rel    ,na.rm=TRUE),
    wds_clean_rel_mn          = mean(wds_clean_rel  ,na.rm=TRUE),
    
    lns_all_fst                = first(lns_all        ),
    wds_raw_all_fst            = first(wds_raw_all    ),
    wds_clean_all_fst          = first(wds_clean_all  ),
    lns_rel_fst                = first(lns_rel        ),
    wds_raw_rel_fst            = first(wds_raw_rel    ),
    wds_clean_rel_fst          = first(wds_clean_rel  ),
    
    lns_all_lst                = last(lns_all        ),
    wds_raw_all_lst            = last(wds_raw_all    ),
    wds_clean_all_lst          = last(wds_clean_all  ),
    lns_rel_lst                = last(lns_rel        ),
    wds_raw_rel_lst            = last(wds_raw_rel    ),
    wds_clean_rel_lst          = last(wds_clean_rel  ),
    
    lns_mdf_sum                = sum(lns_all           ,na.rm=TRUE)    ,
    wds_mdf_sum                = sum(wds_mdf           ,na.rm=TRUE)    ,
    pro_maj_mdf_sum            = sum(pro_maj_mdf       ,na.rm=TRUE)    ,
    pro_min_mdf_sum            = sum(pro_min_mdf       ,na.rm=TRUE)    ,
    pro_non_mdf_sum            = sum(pro_non_mdf       ,na.rm=TRUE)    ,
    wds_pro_maj_mdf_sum        = sum(wds_pro_maj_mdf   ,na.rm=TRUE)    ,
    wds_pro_min_mdf_sum        = sum(wds_pro_min_mdf   ,na.rm=TRUE)    ,
    wds_pro_non_mdf_sum        = sum(wds_pro_non_mdf   ,na.rm=TRUE)    ,
    wds_ins_sum                = sum(wds_ins           ,na.rm=TRUE)    ,
    lns_ins_sum                = sum(lns_ins           ,na.rm=TRUE)    ,
    pro_maj_ins_sum            = sum(pro_maj_ins       ,na.rm=TRUE)    ,
    pro_min_ins_sum            = sum(pro_min_ins       ,na.rm=TRUE)    ,
    pro_non_ins_sum            = sum(pro_non_ins       ,na.rm=TRUE)    ,
    wds_pro_maj_ins_sum        = sum(wds_pro_maj_ins   ,na.rm=TRUE)    ,
    wds_pro_min_ins_sum        = sum(wds_pro_min_ins   ,na.rm=TRUE)    ,
    wds_pro_non_ins_sum        = sum(wds_pro_non_ins   ,na.rm=TRUE)    ,
    wds_del_sum                = sum(wds_del           ,na.rm=TRUE)    ,
    lns_del_sum                = sum(lns_del           ,na.rm=TRUE)    ,
    pro_maj_del_sum            = sum(pro_maj_del       ,na.rm=TRUE)    ,
    pro_min_del_sum            = sum(pro_min_del       ,na.rm=TRUE)    ,
    pro_non_del_sum            = sum(pro_non_del       ,na.rm=TRUE)    ,
    wds_pro_maj_del_sum        = sum(wds_pro_maj_del   ,na.rm=TRUE)    ,
    wds_pro_min_del_sum        = sum(wds_pro_min_del   ,na.rm=TRUE)    ,
    wds_pro_non_del_sum        = sum(wds_pro_non_del   ,na.rm=TRUE)    ,
    pro_maj_sum                = sum(pro_maj           ,na.rm=TRUE)    ,
    pro_min_sum                = sum(pro_min           ,na.rm=TRUE)    ,
    pro_non_sum                = sum(pro_non           ,na.rm=TRUE)    ,
    wds_pro_maj_sum            = sum(wds_pro_maj       ,na.rm=TRUE)    ,
    wds_pro_min_sum            = sum(wds_pro_min       ,na.rm=TRUE)    ,
    wds_pro_non_sum            = sum(wds_pro_non       ,na.rm=TRUE)    ,
    lns_chg_sum                = sum(lns_chg           ,na.rm=TRUE)    ,
    wds_chg_sum                = sum(wds_chg           ,na.rm=TRUE)    ,
    
    lns_corp_8_fst             = first(lns_corp_8            ),
    lns_corp_9_fst             = first(lns_corp_9            ),
    lns_corp_10_fst            = first(lns_corp_10           ),
    lns_corp_21_fst            = first(lns_corp_21           ),
    lns_corp_22_fst            = first(lns_corp_22           ),
    lns_corp_23_fst            = first(lns_corp_23           ),
    lns_corp_25_fst            = first(lns_corp_25           ),
    lns_corp_26_fst            = first(lns_corp_26           ),
    lns_corp_27_fst            = first(lns_corp_27           ),
    lns_corp_28_fst            = first(lns_corp_28           ),
    lns_corp_29_fst            = first(lns_corp_29           ),
    lns_corp_31_fst            = first(lns_corp_31           ),
    lns_corp_32_fst            = first(lns_corp_32           ),
    lns_corp_33_fst            = first(lns_corp_33           ),
    lns_corp_34_fst            = first(lns_corp_34           ),
    lns_corp_43_fst            = first(lns_corp_43           ),
    lns_corp_45_fst            = first(lns_corp_45           ),
    lns_corp_51_fst            = first(lns_corp_51           ),
    lns_corp_52_fst            = first(lns_corp_52           ),
    lns_corp_53_fst            = first(lns_corp_53           ),
    lns_corp_54_fst            = first(lns_corp_54           ),
    lns_corp_55_fst            = first(lns_corp_55           ),
    lns_corp_56_fst            = first(lns_corp_56           ),
    lns_corp_66_fst            = first(lns_corp_66           ),
    lns_corp_67_fst            = first(lns_corp_67           ),
    lns_corp_68_fst            = first(lns_corp_68           ),
    lns_corp_71_fst            = first(lns_corp_71           ),
    lns_corp_72_fst            = first(lns_corp_72           ),
    lns_corp_73_fst            = first(lns_corp_73           ),
    lns_corp_111_fst           = first(lns_corp_111          ),
    lns_corp_112_fst           = first(lns_corp_112          ),
    lns_corp_113_fst           = first(lns_corp_113          ),
    lns_corp_114_fst           = first(lns_corp_114          ),
    lns_corp_121_fst           = first(lns_corp_121          ),
    lns_corp_122_fst           = first(lns_corp_122          ),
    lns_corp_123_fst           = first(lns_corp_123          ),
    lns_corp_124_fst           = first(lns_corp_124          ),
    lns_corp_125_fst           = first(lns_corp_125          ),
    lns_corp_131_fst           = first(lns_corp_131          ),
    lns_corp_132_fst           = first(lns_corp_132          ),
    lns_corp_133_fst           = first(lns_corp_133          ),
    lns_corp_134_fst           = first(lns_corp_134          ),
    lns_corp_141_fst           = first(lns_corp_141          ),
    lns_corp_142_fst           = first(lns_corp_142          ),
    lns_corp_143_fst           = first(lns_corp_143          ),
    lns_corp_144_fst           = first(lns_corp_144          ),
    lns_corp_145_fst           = first(lns_corp_145          ),
    lns_corp_241_fst           = first(lns_corp_241          ),
    lns_corp_242_fst           = first(lns_corp_242          ),
    lns_corp_243_fst           = first(lns_corp_243          ),
    lns_corp_244_fst           = first(lns_corp_244          ),
    lns_corp_411_fst           = first(lns_corp_411          ),
    lns_corp_412_fst           = first(lns_corp_412          ),
    lns_corp_421_fst           = first(lns_corp_421          ),
    lns_corp_422_fst           = first(lns_corp_422          ),
    lns_corp_441_fst           = first(lns_corp_441          ),
    lns_corp_442_fst           = first(lns_corp_442          ),
    lns_corp_611_fst           = first(lns_corp_611          ),
    lns_corp_612_fst           = first(lns_corp_612          ),
    lns_corp_613_fst           = first(lns_corp_613          ),
    lns_corp_631_fst           = first(lns_corp_631          ),
    lns_corp_632_fst           = first(lns_corp_632          ),
    lns_corp_633_fst           = first(lns_corp_633          ),
    lns_corp_634_fst           = first(lns_corp_634          ),
    lns_corp_636_fst           = first(lns_corp_636          ),
    lns_corp_637_fst           = first(lns_corp_637          ),
    lns_corp_638_fst           = first(lns_corp_638          ),
    lns_corp_639_fst           = first(lns_corp_639          ),
    lns_corp_641_fst           = first(lns_corp_641          ),
    lns_corp_642_fst           = first(lns_corp_642          ),
    lns_corp_643_fst           = first(lns_corp_643          ),
    lns_corp_651_fst           = first(lns_corp_651          ),
    lns_corp_652_fst           = first(lns_corp_652          ),
    lns_corp_653_fst           = first(lns_corp_653          ),
    lns_corp_999_fst           = first(lns_corp_999          ),
    lns_corp_6211_fst          = first(lns_corp_6211         ),
    lns_corp_6212_fst          = first(lns_corp_6212         ),
    lns_corp_6221_fst          = first(lns_corp_6221         ),
    lns_corp_6222_fst          = first(lns_corp_6222         ),
    lns_corp_6351_fst          = first(lns_corp_6351         ),
    lns_corp_6352_fst          = first(lns_corp_6352         ),
    wds_corp_8_fst             = first(wds_corp_8            ),
    wds_corp_9_fst             = first(wds_corp_9            ),
    wds_corp_10_fst            = first(wds_corp_10           ),
    wds_corp_21_fst            = first(wds_corp_21           ),
    wds_corp_22_fst            = first(wds_corp_22           ),
    wds_corp_23_fst            = first(wds_corp_23           ),
    wds_corp_25_fst            = first(wds_corp_25           ),
    wds_corp_26_fst            = first(wds_corp_26           ),
    wds_corp_27_fst            = first(wds_corp_27           ),
    wds_corp_28_fst            = first(wds_corp_28           ),
    wds_corp_29_fst            = first(wds_corp_29           ),
    wds_corp_31_fst            = first(wds_corp_31           ),
    wds_corp_32_fst            = first(wds_corp_32           ),
    wds_corp_33_fst            = first(wds_corp_33           ),
    wds_corp_34_fst            = first(wds_corp_34           ),
    wds_corp_43_fst            = first(wds_corp_43           ),
    wds_corp_45_fst            = first(wds_corp_45           ),
    wds_corp_51_fst            = first(wds_corp_51           ),
    wds_corp_52_fst            = first(wds_corp_52           ),
    wds_corp_53_fst            = first(wds_corp_53           ),
    wds_corp_54_fst            = first(wds_corp_54           ),
    wds_corp_55_fst            = first(wds_corp_55           ),
    wds_corp_56_fst            = first(wds_corp_56           ),
    wds_corp_66_fst            = first(wds_corp_66           ),
    wds_corp_67_fst            = first(wds_corp_67           ),
    wds_corp_68_fst            = first(wds_corp_68           ),
    wds_corp_71_fst            = first(wds_corp_71           ),
    wds_corp_72_fst            = first(wds_corp_72           ),
    wds_corp_73_fst            = first(wds_corp_73           ),
    wds_corp_111_fst           = first(wds_corp_111          ),
    wds_corp_112_fst           = first(wds_corp_112          ),
    wds_corp_113_fst           = first(wds_corp_113          ),
    wds_corp_114_fst           = first(wds_corp_114          ),
    wds_corp_121_fst           = first(wds_corp_121          ),
    wds_corp_122_fst           = first(wds_corp_122          ),
    wds_corp_123_fst           = first(wds_corp_123          ),
    wds_corp_124_fst           = first(wds_corp_124          ),
    wds_corp_125_fst           = first(wds_corp_125          ),
    wds_corp_131_fst           = first(wds_corp_131          ),
    wds_corp_132_fst           = first(wds_corp_132          ),
    wds_corp_133_fst           = first(wds_corp_133          ),
    wds_corp_134_fst           = first(wds_corp_134          ),
    wds_corp_141_fst           = first(wds_corp_141          ),
    wds_corp_142_fst           = first(wds_corp_142          ),
    wds_corp_143_fst           = first(wds_corp_143          ),
    wds_corp_144_fst           = first(wds_corp_144          ),
    wds_corp_145_fst           = first(wds_corp_145          ),
    wds_corp_241_fst           = first(wds_corp_241          ),
    wds_corp_242_fst           = first(wds_corp_242          ),
    wds_corp_243_fst           = first(wds_corp_243          ),
    wds_corp_244_fst           = first(wds_corp_244          ),
    wds_corp_411_fst           = first(wds_corp_411          ),
    wds_corp_412_fst           = first(wds_corp_412          ),
    wds_corp_421_fst           = first(wds_corp_421          ),
    wds_corp_422_fst           = first(wds_corp_422          ),
    wds_corp_441_fst           = first(wds_corp_441          ),
    wds_corp_442_fst           = first(wds_corp_442          ),
    wds_corp_611_fst           = first(wds_corp_611          ),
    wds_corp_612_fst           = first(wds_corp_612          ),
    wds_corp_613_fst           = first(wds_corp_613          ),
    wds_corp_631_fst           = first(wds_corp_631          ),
    wds_corp_632_fst           = first(wds_corp_632          ),
    wds_corp_633_fst           = first(wds_corp_633          ),
    wds_corp_634_fst           = first(wds_corp_634          ),
    wds_corp_636_fst           = first(wds_corp_636          ),
    wds_corp_637_fst           = first(wds_corp_637          ),
    wds_corp_638_fst           = first(wds_corp_638          ),
    wds_corp_639_fst           = first(wds_corp_639          ),
    wds_corp_641_fst           = first(wds_corp_641          ),
    wds_corp_642_fst           = first(wds_corp_642          ),
    wds_corp_643_fst           = first(wds_corp_643          ),
    wds_corp_651_fst           = first(wds_corp_651          ),
    wds_corp_652_fst           = first(wds_corp_652          ),
    wds_corp_653_fst           = first(wds_corp_653          ),
    wds_corp_999_fst           = first(wds_corp_999          ),
    wds_corp_6211_fst          = first(wds_corp_6211         ),
    wds_corp_6212_fst          = first(wds_corp_6212         ),
    wds_corp_6221_fst          = first(wds_corp_6221         ),
    wds_corp_6222_fst          = first(wds_corp_6222         ),
    wds_corp_6351_fst          = first(wds_corp_6351         ),
    wds_corp_6352_fst          = first(wds_corp_6352         ),
    lns_corp_top_1_fst         = first(lns_corp_top_1        ),
    lns_corp_top_2_fst         = first(lns_corp_top_2        ),
    lns_corp_top_3_fst         = first(lns_corp_top_3        ),
    lns_corp_top_4_fst         = first(lns_corp_top_4        ),
    lns_corp_top_5_fst         = first(lns_corp_top_5        ),
    lns_corp_top_66_fst        = first(lns_corp_top_66       ),
    lns_corp_top_77_fst        = first(lns_corp_top_77       ),
    wds_corp_top_1_fst         = first(wds_corp_top_1        ),
    wds_corp_top_2_fst         = first(wds_corp_top_2        ),
    wds_corp_top_3_fst         = first(wds_corp_top_3        ),
    wds_corp_top_4_fst         = first(wds_corp_top_4        ),
    wds_corp_top_5_fst         = first(wds_corp_top_5        ),
    wds_corp_top_66_fst        = first(wds_corp_top_66       ),
    wds_corp_top_77_fst        = first(wds_corp_top_77       ),
    lns_corp_act_1_fst         = first(lns_corp_act_1        ),
    lns_corp_act_2_fst         = first(lns_corp_act_2        ),
    lns_corp_act_3_fst         = first(lns_corp_act_3        ),
    lns_corp_act_4_fst         = first(lns_corp_act_4        ),
    lns_corp_act_66_fst        = first(lns_corp_act_66       ),
    lns_corp_act_77_fst        = first(lns_corp_act_77       ),
    wds_corp_act_1_fst         = first(wds_corp_act_1        ),
    wds_corp_act_2_fst         = first(wds_corp_act_2        ),
    wds_corp_act_3_fst         = first(wds_corp_act_3        ),
    wds_corp_act_4_fst         = first(wds_corp_act_4        ),
    wds_corp_act_66_fst        = first(wds_corp_act_66       ),
    wds_corp_act_77_fst        = first(wds_corp_act_77       ),
    
    lns_corp_8_lst             = last(lns_corp_8            ),
    lns_corp_9_lst             = last(lns_corp_9            ),
    lns_corp_10_lst            = last(lns_corp_10           ),
    lns_corp_21_lst            = last(lns_corp_21           ),
    lns_corp_22_lst            = last(lns_corp_22           ),
    lns_corp_23_lst            = last(lns_corp_23           ),
    lns_corp_25_lst            = last(lns_corp_25           ),
    lns_corp_26_lst            = last(lns_corp_26           ),
    lns_corp_27_lst            = last(lns_corp_27           ),
    lns_corp_28_lst            = last(lns_corp_28           ),
    lns_corp_29_lst            = last(lns_corp_29           ),
    lns_corp_31_lst            = last(lns_corp_31           ),
    lns_corp_32_lst            = last(lns_corp_32           ),
    lns_corp_33_lst            = last(lns_corp_33           ),
    lns_corp_34_lst            = last(lns_corp_34           ),
    lns_corp_43_lst            = last(lns_corp_43           ),
    lns_corp_45_lst            = last(lns_corp_45           ),
    lns_corp_51_lst            = last(lns_corp_51           ),
    lns_corp_52_lst            = last(lns_corp_52           ),
    lns_corp_53_lst            = last(lns_corp_53           ),
    lns_corp_54_lst            = last(lns_corp_54           ),
    lns_corp_55_lst            = last(lns_corp_55           ),
    lns_corp_56_lst            = last(lns_corp_56           ),
    lns_corp_66_lst            = last(lns_corp_66           ),
    lns_corp_67_lst            = last(lns_corp_67           ),
    lns_corp_68_lst            = last(lns_corp_68           ),
    lns_corp_71_lst            = last(lns_corp_71           ),
    lns_corp_72_lst            = last(lns_corp_72           ),
    lns_corp_73_lst            = last(lns_corp_73           ),
    lns_corp_111_lst           = last(lns_corp_111          ),
    lns_corp_112_lst           = last(lns_corp_112          ),
    lns_corp_113_lst           = last(lns_corp_113          ),
    lns_corp_114_lst           = last(lns_corp_114          ),
    lns_corp_121_lst           = last(lns_corp_121          ),
    lns_corp_122_lst           = last(lns_corp_122          ),
    lns_corp_123_lst           = last(lns_corp_123          ),
    lns_corp_124_lst           = last(lns_corp_124          ),
    lns_corp_125_lst           = last(lns_corp_125          ),
    lns_corp_131_lst           = last(lns_corp_131          ),
    lns_corp_132_lst           = last(lns_corp_132          ),
    lns_corp_133_lst           = last(lns_corp_133          ),
    lns_corp_134_lst           = last(lns_corp_134          ),
    lns_corp_141_lst           = last(lns_corp_141          ),
    lns_corp_142_lst           = last(lns_corp_142          ),
    lns_corp_143_lst           = last(lns_corp_143          ),
    lns_corp_144_lst           = last(lns_corp_144          ),
    lns_corp_145_lst           = last(lns_corp_145          ),
    lns_corp_241_lst           = last(lns_corp_241          ),
    lns_corp_242_lst           = last(lns_corp_242          ),
    lns_corp_243_lst           = last(lns_corp_243          ),
    lns_corp_244_lst           = last(lns_corp_244          ),
    lns_corp_411_lst           = last(lns_corp_411          ),
    lns_corp_412_lst           = last(lns_corp_412          ),
    lns_corp_421_lst           = last(lns_corp_421          ),
    lns_corp_422_lst           = last(lns_corp_422          ),
    lns_corp_441_lst           = last(lns_corp_441          ),
    lns_corp_442_lst           = last(lns_corp_442          ),
    lns_corp_611_lst           = last(lns_corp_611          ),
    lns_corp_612_lst           = last(lns_corp_612          ),
    lns_corp_613_lst           = last(lns_corp_613          ),
    lns_corp_631_lst           = last(lns_corp_631          ),
    lns_corp_632_lst           = last(lns_corp_632          ),
    lns_corp_633_lst           = last(lns_corp_633          ),
    lns_corp_634_lst           = last(lns_corp_634          ),
    lns_corp_636_lst           = last(lns_corp_636          ),
    lns_corp_637_lst           = last(lns_corp_637          ),
    lns_corp_638_lst           = last(lns_corp_638          ),
    lns_corp_639_lst           = last(lns_corp_639          ),
    lns_corp_641_lst           = last(lns_corp_641          ),
    lns_corp_642_lst           = last(lns_corp_642          ),
    lns_corp_643_lst           = last(lns_corp_643          ),
    lns_corp_651_lst           = last(lns_corp_651          ),
    lns_corp_652_lst           = last(lns_corp_652          ),
    lns_corp_653_lst           = last(lns_corp_653          ),
    lns_corp_999_lst           = last(lns_corp_999          ),
    lns_corp_6211_lst          = last(lns_corp_6211         ),
    lns_corp_6212_lst          = last(lns_corp_6212         ),
    lns_corp_6221_lst          = last(lns_corp_6221         ),
    lns_corp_6222_lst          = last(lns_corp_6222         ),
    lns_corp_6351_lst          = last(lns_corp_6351         ),
    lns_corp_6352_lst          = last(lns_corp_6352         ),
    wds_corp_8_lst             = last(wds_corp_8            ),
    wds_corp_9_lst             = last(wds_corp_9            ),
    wds_corp_10_lst            = last(wds_corp_10           ),
    wds_corp_21_lst            = last(wds_corp_21           ),
    wds_corp_22_lst            = last(wds_corp_22           ),
    wds_corp_23_lst            = last(wds_corp_23           ),
    wds_corp_25_lst            = last(wds_corp_25           ),
    wds_corp_26_lst            = last(wds_corp_26           ),
    wds_corp_27_lst            = last(wds_corp_27           ),
    wds_corp_28_lst            = last(wds_corp_28           ),
    wds_corp_29_lst            = last(wds_corp_29           ),
    wds_corp_31_lst            = last(wds_corp_31           ),
    wds_corp_32_lst            = last(wds_corp_32           ),
    wds_corp_33_lst            = last(wds_corp_33           ),
    wds_corp_34_lst            = last(wds_corp_34           ),
    wds_corp_43_lst            = last(wds_corp_43           ),
    wds_corp_45_lst            = last(wds_corp_45           ),
    wds_corp_51_lst            = last(wds_corp_51           ),
    wds_corp_52_lst            = last(wds_corp_52           ),
    wds_corp_53_lst            = last(wds_corp_53           ),
    wds_corp_54_lst            = last(wds_corp_54           ),
    wds_corp_55_lst            = last(wds_corp_55           ),
    wds_corp_56_lst            = last(wds_corp_56           ),
    wds_corp_66_lst            = last(wds_corp_66           ),
    wds_corp_67_lst            = last(wds_corp_67           ),
    wds_corp_68_lst            = last(wds_corp_68           ),
    wds_corp_71_lst            = last(wds_corp_71           ),
    wds_corp_72_lst            = last(wds_corp_72           ),
    wds_corp_73_lst            = last(wds_corp_73           ),
    wds_corp_111_lst           = last(wds_corp_111          ),
    wds_corp_112_lst           = last(wds_corp_112          ),
    wds_corp_113_lst           = last(wds_corp_113          ),
    wds_corp_114_lst           = last(wds_corp_114          ),
    wds_corp_121_lst           = last(wds_corp_121          ),
    wds_corp_122_lst           = last(wds_corp_122          ),
    wds_corp_123_lst           = last(wds_corp_123          ),
    wds_corp_124_lst           = last(wds_corp_124          ),
    wds_corp_125_lst           = last(wds_corp_125          ),
    wds_corp_131_lst           = last(wds_corp_131          ),
    wds_corp_132_lst           = last(wds_corp_132          ),
    wds_corp_133_lst           = last(wds_corp_133          ),
    wds_corp_134_lst           = last(wds_corp_134          ),
    wds_corp_141_lst           = last(wds_corp_141          ),
    wds_corp_142_lst           = last(wds_corp_142          ),
    wds_corp_143_lst           = last(wds_corp_143          ),
    wds_corp_144_lst           = last(wds_corp_144          ),
    wds_corp_145_lst           = last(wds_corp_145          ),
    wds_corp_241_lst           = last(wds_corp_241          ),
    wds_corp_242_lst           = last(wds_corp_242          ),
    wds_corp_243_lst           = last(wds_corp_243          ),
    wds_corp_244_lst           = last(wds_corp_244          ),
    wds_corp_411_lst           = last(wds_corp_411          ),
    wds_corp_412_lst           = last(wds_corp_412          ),
    wds_corp_421_lst           = last(wds_corp_421          ),
    wds_corp_422_lst           = last(wds_corp_422          ),
    wds_corp_441_lst           = last(wds_corp_441          ),
    wds_corp_442_lst           = last(wds_corp_442          ),
    wds_corp_611_lst           = last(wds_corp_611          ),
    wds_corp_612_lst           = last(wds_corp_612          ),
    wds_corp_613_lst           = last(wds_corp_613          ),
    wds_corp_631_lst           = last(wds_corp_631          ),
    wds_corp_632_lst           = last(wds_corp_632          ),
    wds_corp_633_lst           = last(wds_corp_633          ),
    wds_corp_634_lst           = last(wds_corp_634          ),
    wds_corp_636_lst           = last(wds_corp_636          ),
    wds_corp_637_lst           = last(wds_corp_637          ),
    wds_corp_638_lst           = last(wds_corp_638          ),
    wds_corp_639_lst           = last(wds_corp_639          ),
    wds_corp_641_lst           = last(wds_corp_641          ),
    wds_corp_642_lst           = last(wds_corp_642          ),
    wds_corp_643_lst           = last(wds_corp_643          ),
    wds_corp_651_lst           = last(wds_corp_651          ),
    wds_corp_652_lst           = last(wds_corp_652          ),
    wds_corp_653_lst           = last(wds_corp_653          ),
    wds_corp_999_lst           = last(wds_corp_999          ),
    wds_corp_6211_lst          = last(wds_corp_6211         ),
    wds_corp_6212_lst          = last(wds_corp_6212         ),
    wds_corp_6221_lst          = last(wds_corp_6221         ),
    wds_corp_6222_lst          = last(wds_corp_6222         ),
    wds_corp_6351_lst          = last(wds_corp_6351         ),
    wds_corp_6352_lst          = last(wds_corp_6352         ),
    lns_corp_top_1_lst         = last(lns_corp_top_1        ),
    lns_corp_top_2_lst         = last(lns_corp_top_2        ),
    lns_corp_top_3_lst         = last(lns_corp_top_3        ),
    lns_corp_top_4_lst         = last(lns_corp_top_4        ),
    lns_corp_top_5_lst         = last(lns_corp_top_5        ),
    lns_corp_top_66_lst        = last(lns_corp_top_66       ),
    lns_corp_top_77_lst        = last(lns_corp_top_77       ),
    wds_corp_top_1_lst         = last(wds_corp_top_1        ),
    wds_corp_top_2_lst         = last(wds_corp_top_2        ),
    wds_corp_top_3_lst         = last(wds_corp_top_3        ),
    wds_corp_top_4_lst         = last(wds_corp_top_4        ),
    wds_corp_top_5_lst         = last(wds_corp_top_5        ),
    wds_corp_top_66_lst        = last(wds_corp_top_66       ),
    wds_corp_top_77_lst        = last(wds_corp_top_77       ),
    lns_corp_act_1_lst         = last(lns_corp_act_1        ),
    lns_corp_act_2_lst         = last(lns_corp_act_2        ),
    lns_corp_act_3_lst         = last(lns_corp_act_3        ),
    lns_corp_act_4_lst         = last(lns_corp_act_4        ),
    lns_corp_act_66_lst        = last(lns_corp_act_66       ),
    lns_corp_act_77_lst        = last(lns_corp_act_77       ),
    wds_corp_act_1_lst         = last(wds_corp_act_1        ),
    wds_corp_act_2_lst         = last(wds_corp_act_2        ),
    wds_corp_act_3_lst         = last(wds_corp_act_3        ),
    wds_corp_act_4_lst         = last(wds_corp_act_4        ),
    wds_corp_act_66_lst        = last(wds_corp_act_66       ),
    wds_corp_act_77_lst        = last(wds_corp_act_77       ),
    
    lns_corp_8_mn             = mean(lns_corp_8            ,na.rm=TRUE),
    lns_corp_9_mn             = mean(lns_corp_9            ,na.rm=TRUE),
    lns_corp_10_mn            = mean(lns_corp_10           ,na.rm=TRUE),
    lns_corp_21_mn            = mean(lns_corp_21           ,na.rm=TRUE),
    lns_corp_22_mn            = mean(lns_corp_22           ,na.rm=TRUE),
    lns_corp_23_mn            = mean(lns_corp_23           ,na.rm=TRUE),
    lns_corp_25_mn            = mean(lns_corp_25           ,na.rm=TRUE),
    lns_corp_26_mn            = mean(lns_corp_26           ,na.rm=TRUE),
    lns_corp_27_mn            = mean(lns_corp_27           ,na.rm=TRUE),
    lns_corp_28_mn            = mean(lns_corp_28           ,na.rm=TRUE),
    lns_corp_29_mn            = mean(lns_corp_29           ,na.rm=TRUE),
    lns_corp_31_mn            = mean(lns_corp_31           ,na.rm=TRUE),
    lns_corp_32_mn            = mean(lns_corp_32           ,na.rm=TRUE),
    lns_corp_33_mn            = mean(lns_corp_33           ,na.rm=TRUE),
    lns_corp_34_mn            = mean(lns_corp_34           ,na.rm=TRUE),
    lns_corp_43_mn            = mean(lns_corp_43           ,na.rm=TRUE),
    lns_corp_45_mn            = mean(lns_corp_45           ,na.rm=TRUE),
    lns_corp_51_mn            = mean(lns_corp_51           ,na.rm=TRUE),
    lns_corp_52_mn            = mean(lns_corp_52           ,na.rm=TRUE),
    lns_corp_53_mn            = mean(lns_corp_53           ,na.rm=TRUE),
    lns_corp_54_mn            = mean(lns_corp_54           ,na.rm=TRUE),
    lns_corp_55_mn            = mean(lns_corp_55           ,na.rm=TRUE),
    lns_corp_56_mn            = mean(lns_corp_56           ,na.rm=TRUE),
    lns_corp_66_mn            = mean(lns_corp_66           ,na.rm=TRUE),
    lns_corp_67_mn            = mean(lns_corp_67           ,na.rm=TRUE),
    lns_corp_68_mn            = mean(lns_corp_68           ,na.rm=TRUE),
    lns_corp_71_mn            = mean(lns_corp_71           ,na.rm=TRUE),
    lns_corp_72_mn            = mean(lns_corp_72           ,na.rm=TRUE),
    lns_corp_73_mn            = mean(lns_corp_73           ,na.rm=TRUE),
    lns_corp_111_mn           = mean(lns_corp_111          ,na.rm=TRUE),
    lns_corp_112_mn           = mean(lns_corp_112          ,na.rm=TRUE),
    lns_corp_113_mn           = mean(lns_corp_113          ,na.rm=TRUE),
    lns_corp_114_mn           = mean(lns_corp_114          ,na.rm=TRUE),
    lns_corp_121_mn           = mean(lns_corp_121          ,na.rm=TRUE),
    lns_corp_122_mn           = mean(lns_corp_122          ,na.rm=TRUE),
    lns_corp_123_mn           = mean(lns_corp_123          ,na.rm=TRUE),
    lns_corp_124_mn           = mean(lns_corp_124          ,na.rm=TRUE),
    lns_corp_125_mn           = mean(lns_corp_125          ,na.rm=TRUE),
    lns_corp_131_mn           = mean(lns_corp_131          ,na.rm=TRUE),
    lns_corp_132_mn           = mean(lns_corp_132          ,na.rm=TRUE),
    lns_corp_133_mn           = mean(lns_corp_133          ,na.rm=TRUE),
    lns_corp_134_mn           = mean(lns_corp_134          ,na.rm=TRUE),
    lns_corp_141_mn           = mean(lns_corp_141          ,na.rm=TRUE),
    lns_corp_142_mn           = mean(lns_corp_142          ,na.rm=TRUE),
    lns_corp_143_mn           = mean(lns_corp_143          ,na.rm=TRUE),
    lns_corp_144_mn           = mean(lns_corp_144          ,na.rm=TRUE),
    lns_corp_145_mn           = mean(lns_corp_145          ,na.rm=TRUE),
    lns_corp_241_mn           = mean(lns_corp_241          ,na.rm=TRUE),
    lns_corp_242_mn           = mean(lns_corp_242          ,na.rm=TRUE),
    lns_corp_243_mn           = mean(lns_corp_243          ,na.rm=TRUE),
    lns_corp_244_mn           = mean(lns_corp_244          ,na.rm=TRUE),
    lns_corp_411_mn           = mean(lns_corp_411          ,na.rm=TRUE),
    lns_corp_412_mn           = mean(lns_corp_412          ,na.rm=TRUE),
    lns_corp_421_mn           = mean(lns_corp_421          ,na.rm=TRUE),
    lns_corp_422_mn           = mean(lns_corp_422          ,na.rm=TRUE),
    lns_corp_441_mn           = mean(lns_corp_441          ,na.rm=TRUE),
    lns_corp_442_mn           = mean(lns_corp_442          ,na.rm=TRUE),
    lns_corp_611_mn           = mean(lns_corp_611          ,na.rm=TRUE),
    lns_corp_612_mn           = mean(lns_corp_612          ,na.rm=TRUE),
    lns_corp_613_mn           = mean(lns_corp_613          ,na.rm=TRUE),
    lns_corp_631_mn           = mean(lns_corp_631          ,na.rm=TRUE),
    lns_corp_632_mn           = mean(lns_corp_632          ,na.rm=TRUE),
    lns_corp_633_mn           = mean(lns_corp_633          ,na.rm=TRUE),
    lns_corp_634_mn           = mean(lns_corp_634          ,na.rm=TRUE),
    lns_corp_636_mn           = mean(lns_corp_636          ,na.rm=TRUE),
    lns_corp_637_mn           = mean(lns_corp_637          ,na.rm=TRUE),
    lns_corp_638_mn           = mean(lns_corp_638          ,na.rm=TRUE),
    lns_corp_639_mn           = mean(lns_corp_639          ,na.rm=TRUE),
    lns_corp_641_mn           = mean(lns_corp_641          ,na.rm=TRUE),
    lns_corp_642_mn           = mean(lns_corp_642          ,na.rm=TRUE),
    lns_corp_643_mn           = mean(lns_corp_643          ,na.rm=TRUE),
    lns_corp_651_mn           = mean(lns_corp_651          ,na.rm=TRUE),
    lns_corp_652_mn           = mean(lns_corp_652          ,na.rm=TRUE),
    lns_corp_653_mn           = mean(lns_corp_653          ,na.rm=TRUE),
    lns_corp_999_mn           = mean(lns_corp_999          ,na.rm=TRUE),
    lns_corp_6211_mn          = mean(lns_corp_6211         ,na.rm=TRUE),
    lns_corp_6212_mn          = mean(lns_corp_6212         ,na.rm=TRUE),
    lns_corp_6221_mn          = mean(lns_corp_6221         ,na.rm=TRUE),
    lns_corp_6222_mn          = mean(lns_corp_6222         ,na.rm=TRUE),
    lns_corp_6351_mn          = mean(lns_corp_6351         ,na.rm=TRUE),
    lns_corp_6352_mn          = mean(lns_corp_6352         ,na.rm=TRUE),
    wds_corp_8_mn             = mean(wds_corp_8            ,na.rm=TRUE),
    wds_corp_9_mn             = mean(wds_corp_9            ,na.rm=TRUE),
    wds_corp_10_mn            = mean(wds_corp_10           ,na.rm=TRUE),
    wds_corp_21_mn            = mean(wds_corp_21           ,na.rm=TRUE),
    wds_corp_22_mn            = mean(wds_corp_22           ,na.rm=TRUE),
    wds_corp_23_mn            = mean(wds_corp_23           ,na.rm=TRUE),
    wds_corp_25_mn            = mean(wds_corp_25           ,na.rm=TRUE),
    wds_corp_26_mn            = mean(wds_corp_26           ,na.rm=TRUE),
    wds_corp_27_mn            = mean(wds_corp_27           ,na.rm=TRUE),
    wds_corp_28_mn            = mean(wds_corp_28           ,na.rm=TRUE),
    wds_corp_29_mn            = mean(wds_corp_29           ,na.rm=TRUE),
    wds_corp_31_mn            = mean(wds_corp_31           ,na.rm=TRUE),
    wds_corp_32_mn            = mean(wds_corp_32           ,na.rm=TRUE),
    wds_corp_33_mn            = mean(wds_corp_33           ,na.rm=TRUE),
    wds_corp_34_mn            = mean(wds_corp_34           ,na.rm=TRUE),
    wds_corp_43_mn            = mean(wds_corp_43           ,na.rm=TRUE),
    wds_corp_45_mn            = mean(wds_corp_45           ,na.rm=TRUE),
    wds_corp_51_mn            = mean(wds_corp_51           ,na.rm=TRUE),
    wds_corp_52_mn            = mean(wds_corp_52           ,na.rm=TRUE),
    wds_corp_53_mn            = mean(wds_corp_53           ,na.rm=TRUE),
    wds_corp_54_mn            = mean(wds_corp_54           ,na.rm=TRUE),
    wds_corp_55_mn            = mean(wds_corp_55           ,na.rm=TRUE),
    wds_corp_56_mn            = mean(wds_corp_56           ,na.rm=TRUE),
    wds_corp_66_mn            = mean(wds_corp_66           ,na.rm=TRUE),
    wds_corp_67_mn            = mean(wds_corp_67           ,na.rm=TRUE),
    wds_corp_68_mn            = mean(wds_corp_68           ,na.rm=TRUE),
    wds_corp_71_mn            = mean(wds_corp_71           ,na.rm=TRUE),
    wds_corp_72_mn            = mean(wds_corp_72           ,na.rm=TRUE),
    wds_corp_73_mn            = mean(wds_corp_73           ,na.rm=TRUE),
    wds_corp_111_mn           = mean(wds_corp_111          ,na.rm=TRUE),
    wds_corp_112_mn           = mean(wds_corp_112          ,na.rm=TRUE),
    wds_corp_113_mn           = mean(wds_corp_113          ,na.rm=TRUE),
    wds_corp_114_mn           = mean(wds_corp_114          ,na.rm=TRUE),
    wds_corp_121_mn           = mean(wds_corp_121          ,na.rm=TRUE),
    wds_corp_122_mn           = mean(wds_corp_122          ,na.rm=TRUE),
    wds_corp_123_mn           = mean(wds_corp_123          ,na.rm=TRUE),
    wds_corp_124_mn           = mean(wds_corp_124          ,na.rm=TRUE),
    wds_corp_125_mn           = mean(wds_corp_125          ,na.rm=TRUE),
    wds_corp_131_mn           = mean(wds_corp_131          ,na.rm=TRUE),
    wds_corp_132_mn           = mean(wds_corp_132          ,na.rm=TRUE),
    wds_corp_133_mn           = mean(wds_corp_133          ,na.rm=TRUE),
    wds_corp_134_mn           = mean(wds_corp_134          ,na.rm=TRUE),
    wds_corp_141_mn           = mean(wds_corp_141          ,na.rm=TRUE),
    wds_corp_142_mn           = mean(wds_corp_142          ,na.rm=TRUE),
    wds_corp_143_mn           = mean(wds_corp_143          ,na.rm=TRUE),
    wds_corp_144_mn           = mean(wds_corp_144          ,na.rm=TRUE),
    wds_corp_145_mn           = mean(wds_corp_145          ,na.rm=TRUE),
    wds_corp_241_mn           = mean(wds_corp_241          ,na.rm=TRUE),
    wds_corp_242_mn           = mean(wds_corp_242          ,na.rm=TRUE),
    wds_corp_243_mn           = mean(wds_corp_243          ,na.rm=TRUE),
    wds_corp_244_mn           = mean(wds_corp_244          ,na.rm=TRUE),
    wds_corp_411_mn           = mean(wds_corp_411          ,na.rm=TRUE),
    wds_corp_412_mn           = mean(wds_corp_412          ,na.rm=TRUE),
    wds_corp_421_mn           = mean(wds_corp_421          ,na.rm=TRUE),
    wds_corp_422_mn           = mean(wds_corp_422          ,na.rm=TRUE),
    wds_corp_441_mn           = mean(wds_corp_441          ,na.rm=TRUE),
    wds_corp_442_mn           = mean(wds_corp_442          ,na.rm=TRUE),
    wds_corp_611_mn           = mean(wds_corp_611          ,na.rm=TRUE),
    wds_corp_612_mn           = mean(wds_corp_612          ,na.rm=TRUE),
    wds_corp_613_mn           = mean(wds_corp_613          ,na.rm=TRUE),
    wds_corp_631_mn           = mean(wds_corp_631          ,na.rm=TRUE),
    wds_corp_632_mn           = mean(wds_corp_632          ,na.rm=TRUE),
    wds_corp_633_mn           = mean(wds_corp_633          ,na.rm=TRUE),
    wds_corp_634_mn           = mean(wds_corp_634          ,na.rm=TRUE),
    wds_corp_636_mn           = mean(wds_corp_636          ,na.rm=TRUE),
    wds_corp_637_mn           = mean(wds_corp_637          ,na.rm=TRUE),
    wds_corp_638_mn           = mean(wds_corp_638          ,na.rm=TRUE),
    wds_corp_639_mn           = mean(wds_corp_639          ,na.rm=TRUE),
    wds_corp_641_mn           = mean(wds_corp_641          ,na.rm=TRUE),
    wds_corp_642_mn           = mean(wds_corp_642          ,na.rm=TRUE),
    wds_corp_643_mn           = mean(wds_corp_643          ,na.rm=TRUE),
    wds_corp_651_mn           = mean(wds_corp_651          ,na.rm=TRUE),
    wds_corp_652_mn           = mean(wds_corp_652          ,na.rm=TRUE),
    wds_corp_653_mn           = mean(wds_corp_653          ,na.rm=TRUE),
    wds_corp_999_mn           = mean(wds_corp_999          ,na.rm=TRUE),
    wds_corp_6211_mn          = mean(wds_corp_6211         ,na.rm=TRUE),
    wds_corp_6212_mn          = mean(wds_corp_6212         ,na.rm=TRUE),
    wds_corp_6221_mn          = mean(wds_corp_6221         ,na.rm=TRUE),
    wds_corp_6222_mn          = mean(wds_corp_6222         ,na.rm=TRUE),
    wds_corp_6351_mn          = mean(wds_corp_6351         ,na.rm=TRUE),
    wds_corp_6352_mn          = mean(wds_corp_6352         ,na.rm=TRUE),
    lns_corp_top_1_mn         = mean(lns_corp_top_1        ,na.rm=TRUE),
    lns_corp_top_2_mn         = mean(lns_corp_top_2        ,na.rm=TRUE),
    lns_corp_top_3_mn         = mean(lns_corp_top_3        ,na.rm=TRUE),
    lns_corp_top_4_mn         = mean(lns_corp_top_4        ,na.rm=TRUE),
    lns_corp_top_5_mn         = mean(lns_corp_top_5        ,na.rm=TRUE),
    lns_corp_top_66_mn        = mean(lns_corp_top_66       ,na.rm=TRUE),
    lns_corp_top_77_mn        = mean(lns_corp_top_77       ,na.rm=TRUE),
    wds_corp_top_1_mn         = mean(wds_corp_top_1        ,na.rm=TRUE),
    wds_corp_top_2_mn         = mean(wds_corp_top_2        ,na.rm=TRUE),
    wds_corp_top_3_mn         = mean(wds_corp_top_3        ,na.rm=TRUE),
    wds_corp_top_4_mn         = mean(wds_corp_top_4        ,na.rm=TRUE),
    wds_corp_top_5_mn         = mean(wds_corp_top_5        ,na.rm=TRUE),
    wds_corp_top_66_mn        = mean(wds_corp_top_66       ,na.rm=TRUE),
    wds_corp_top_77_mn        = mean(wds_corp_top_77       ,na.rm=TRUE),
    lns_corp_act_1_mn         = mean(lns_corp_act_1        ,na.rm=TRUE),
    lns_corp_act_2_mn         = mean(lns_corp_act_2        ,na.rm=TRUE),
    lns_corp_act_3_mn         = mean(lns_corp_act_3        ,na.rm=TRUE),
    lns_corp_act_4_mn         = mean(lns_corp_act_4        ,na.rm=TRUE),
    lns_corp_act_66_mn        = mean(lns_corp_act_66       ,na.rm=TRUE),
    lns_corp_act_77_mn        = mean(lns_corp_act_77       ,na.rm=TRUE),
    wds_corp_act_1_mn         = mean(wds_corp_act_1        ,na.rm=TRUE),
    wds_corp_act_2_mn         = mean(wds_corp_act_2        ,na.rm=TRUE),
    wds_corp_act_3_mn         = mean(wds_corp_act_3        ,na.rm=TRUE),
    wds_corp_act_4_mn         = mean(wds_corp_act_4        ,na.rm=TRUE),
    wds_corp_act_66_mn        = mean(wds_corp_act_66       ,na.rm=TRUE),
    wds_corp_act_77_mn        = mean(wds_corp_act_77       ,na.rm=TRUE),
    
    
    wds_corp_mdf_8_sum         = sum(wds_corp_mdf_8         ,na.rm=TRUE),
    wds_corp_mdf_21_sum        = sum(wds_corp_mdf_21        ,na.rm=TRUE),
    wds_corp_mdf_25_sum        = sum(wds_corp_mdf_25        ,na.rm=TRUE),
    wds_corp_mdf_51_sum        = sum(wds_corp_mdf_51        ,na.rm=TRUE),
    wds_corp_mdf_53_sum        = sum(wds_corp_mdf_53        ,na.rm=TRUE),
    wds_corp_mdf_54_sum        = sum(wds_corp_mdf_54        ,na.rm=TRUE),
    wds_corp_mdf_55_sum        = sum(wds_corp_mdf_55        , na.rm=TRUE),
    wds_corp_mdf_56_sum        = sum(wds_corp_mdf_56        , na.rm=TRUE),
    wds_corp_mdf_68_sum        = sum(wds_corp_mdf_68        , na.rm=TRUE),
    wds_corp_mdf_71_sum        = sum(wds_corp_mdf_71        , na.rm=TRUE),
    wds_corp_mdf_73_sum        = sum(wds_corp_mdf_73        , na.rm=TRUE),
    wds_corp_mdf_111_sum       = sum(wds_corp_mdf_111       , na.rm=TRUE),
    wds_corp_mdf_112_sum       = sum(wds_corp_mdf_112       , na.rm=TRUE),
    wds_corp_mdf_113_sum       = sum(wds_corp_mdf_113       , na.rm=TRUE),
    wds_corp_mdf_121_sum       = sum(wds_corp_mdf_121       , na.rm=TRUE),
    wds_corp_mdf_122_sum       = sum(wds_corp_mdf_122       , na.rm=TRUE),
    wds_corp_mdf_123_sum       = sum(wds_corp_mdf_123       , na.rm=TRUE),
    wds_corp_mdf_125_sum       = sum(wds_corp_mdf_125       , na.rm=TRUE),
    wds_corp_mdf_133_sum       = sum(wds_corp_mdf_133       , na.rm=TRUE),
    wds_corp_mdf_134_sum       = sum(wds_corp_mdf_134       , na.rm=TRUE),
    wds_corp_mdf_142_sum       = sum(wds_corp_mdf_142       , na.rm=TRUE),
    wds_corp_mdf_143_sum       = sum(wds_corp_mdf_143       , na.rm=TRUE),
    wds_corp_mdf_611_sum       = sum(wds_corp_mdf_611       , na.rm=TRUE),
    wds_corp_mdf_612_sum       = sum(wds_corp_mdf_612       , na.rm=TRUE),
    wds_corp_mdf_632_sum       = sum(wds_corp_mdf_632       , na.rm=TRUE),
    wds_corp_mdf_637_sum       = sum(wds_corp_mdf_637       , na.rm=TRUE),
    wds_corp_mdf_651_sum       = sum(wds_corp_mdf_651       , na.rm=TRUE),
    wds_corp_mdf_6211_sum      = sum(wds_corp_mdf_6211      , na.rm=TRUE),
    wds_corp_mdf_6212_sum      = sum(wds_corp_mdf_6212      , na.rm=TRUE),
    wds_corp_mdf_10_sum        = sum(wds_corp_mdf_10        , na.rm=TRUE),
    wds_corp_mdf_26_sum        = sum(wds_corp_mdf_26        , na.rm=TRUE),
    wds_corp_mdf_32_sum        = sum(wds_corp_mdf_32        , na.rm=TRUE),
    wds_corp_mdf_34_sum        = sum(wds_corp_mdf_34        , na.rm=TRUE),
    wds_corp_mdf_52_sum        = sum(wds_corp_mdf_52        , na.rm=TRUE),
    wds_corp_mdf_131_sum       = sum(wds_corp_mdf_131       , na.rm=TRUE),
    wds_corp_mdf_132_sum       = sum(wds_corp_mdf_132       , na.rm=TRUE),
    wds_corp_mdf_412_sum       = sum(wds_corp_mdf_412       , na.rm=TRUE),
    wds_corp_mdf_633_sum       = sum(wds_corp_mdf_633       , na.rm=TRUE),
    wds_corp_mdf_634_sum       = sum(wds_corp_mdf_634       , na.rm=TRUE),
    wds_corp_mdf_636_sum       = sum(wds_corp_mdf_636       , na.rm=TRUE),
    wds_corp_mdf_652_sum       = sum(wds_corp_mdf_652       , na.rm=TRUE),
    wds_corp_mdf_6221_sum      = sum(wds_corp_mdf_6221      , na.rm=TRUE),
    wds_corp_mdf_6222_sum      = sum(wds_corp_mdf_6222      , na.rm=TRUE),
    wds_corp_mdf_411_sum       = sum(wds_corp_mdf_411       , na.rm=TRUE),
    wds_corp_mdf_638_sum       = sum(wds_corp_mdf_638       , na.rm=TRUE),
    wds_corp_mdf_641_sum       = sum(wds_corp_mdf_641       , na.rm=TRUE),
    wds_corp_mdf_22_sum        = sum(wds_corp_mdf_22        , na.rm=TRUE),
    wds_corp_mdf_23_sum        = sum(wds_corp_mdf_23        , na.rm=TRUE),
    wds_corp_mdf_241_sum       = sum(wds_corp_mdf_241       , na.rm=TRUE),
    wds_corp_mdf_613_sum       = sum(wds_corp_mdf_613       , na.rm=TRUE),
    wds_corp_mdf_631_sum       = sum(wds_corp_mdf_631       , na.rm=TRUE),
    wds_corp_mdf_639_sum       = sum(wds_corp_mdf_639       , na.rm=TRUE),
    wds_corp_mdf_6352_sum      = sum(wds_corp_mdf_6352      , na.rm=TRUE),
    wds_corp_mdf_642_sum       = sum(wds_corp_mdf_642       , na.rm=TRUE),
    wds_corp_mdf_29_sum        = sum(wds_corp_mdf_29        , na.rm=TRUE),
    wds_corp_mdf_242_sum       = sum(wds_corp_mdf_242       , na.rm=TRUE),
    wds_corp_mdf_124_sum       = sum(wds_corp_mdf_124       , na.rm=TRUE),
    wds_corp_mdf_643_sum       = sum(wds_corp_mdf_643       , na.rm=TRUE),
    wds_corp_mdf_33_sum        = sum(wds_corp_mdf_33        , na.rm=TRUE),
    wds_corp_mdf_145_sum       = sum(wds_corp_mdf_145       , na.rm=TRUE),
    wds_corp_mdf_72_sum        = sum(wds_corp_mdf_72        , na.rm=TRUE),
    wds_corp_mdf_9_sum         = sum(wds_corp_mdf_9         , na.rm=TRUE),
    wds_corp_mdf_653_sum       = sum(wds_corp_mdf_653       , na.rm=TRUE),
    wds_corp_mdf_6351_sum      = sum(wds_corp_mdf_6351      , na.rm=TRUE),
    wds_corp_mdf_27_sum        = sum(wds_corp_mdf_27        , na.rm=TRUE),
    wds_corp_mdf_442_sum       = sum(wds_corp_mdf_442       , na.rm=TRUE),
    wds_corp_mdf_114_sum       = sum(wds_corp_mdf_114       , na.rm=TRUE),
    wds_corp_mdf_141_sum       = sum(wds_corp_mdf_141       , na.rm=TRUE),
    wds_corp_mdf_244_sum       = sum(wds_corp_mdf_244       , na.rm=TRUE),
    wds_corp_mdf_43_sum        = sum(wds_corp_mdf_43        , na.rm=TRUE),
    wds_corp_mdf_45_sum        = sum(wds_corp_mdf_45        , na.rm=TRUE),
    wds_corp_mdf_31_sum        = sum(wds_corp_mdf_31        , na.rm=TRUE),
    wds_corp_mdf_28_sum        = sum(wds_corp_mdf_28        , na.rm=TRUE),
    wds_corp_mdf_144_sum       = sum(wds_corp_mdf_144       , na.rm=TRUE),
    wds_corp_mdf_421_sum       = sum(wds_corp_mdf_421       , na.rm=TRUE),
    wds_corp_mdf_422_sum       = sum(wds_corp_mdf_422       , na.rm=TRUE),
    wds_corp_mdf_67_sum        = sum(wds_corp_mdf_67        , na.rm=TRUE),
    wds_corp_mdf_243_sum       = sum(wds_corp_mdf_243       , na.rm=TRUE),
    wds_corp_ins_6211_sum      = sum(wds_corp_ins_6211      , na.rm=TRUE),
    wds_corp_ins_8_sum         = sum(wds_corp_ins_8         , na.rm=TRUE),
    wds_corp_ins_9_sum         = sum(wds_corp_ins_9         , na.rm=TRUE),
    wds_corp_ins_51_sum        = sum(wds_corp_ins_51        , na.rm=TRUE),
    wds_corp_ins_53_sum        = sum(wds_corp_ins_53        , na.rm=TRUE),
    wds_corp_ins_111_sum       = sum(wds_corp_ins_111       , na.rm=TRUE),
    wds_corp_ins_121_sum       = sum(wds_corp_ins_121       , na.rm=TRUE),
    wds_corp_ins_125_sum       = sum(wds_corp_ins_125       , na.rm=TRUE),
    wds_corp_ins_412_sum       = sum(wds_corp_ins_412       , na.rm=TRUE),
    wds_corp_ins_632_sum       = sum(wds_corp_ins_632       , na.rm=TRUE),
    wds_corp_ins_633_sum       = sum(wds_corp_ins_633       , na.rm=TRUE),
    wds_corp_ins_634_sum       = sum(wds_corp_ins_634       , na.rm=TRUE),
    wds_corp_ins_637_sum       = sum(wds_corp_ins_637       , na.rm=TRUE),
    wds_corp_ins_641_sum       = sum(wds_corp_ins_641       , na.rm=TRUE),
    wds_corp_ins_651_sum       = sum(wds_corp_ins_651       , na.rm=TRUE),
    wds_corp_ins_6221_sum      = sum(wds_corp_ins_6221      , na.rm=TRUE),
    wds_corp_ins_6222_sum      = sum(wds_corp_ins_6222      , na.rm=TRUE),
    wds_corp_ins_10_sum        = sum(wds_corp_ins_10        , na.rm=TRUE),
    wds_corp_ins_21_sum        = sum(wds_corp_ins_21        , na.rm=TRUE),
    wds_corp_ins_25_sum        = sum(wds_corp_ins_25        , na.rm=TRUE),
    wds_corp_ins_26_sum        = sum(wds_corp_ins_26        , na.rm=TRUE),
    wds_corp_ins_32_sum        = sum(wds_corp_ins_32        , na.rm=TRUE),
    wds_corp_ins_34_sum        = sum(wds_corp_ins_34        , na.rm=TRUE),
    wds_corp_ins_52_sum        = sum(wds_corp_ins_52        , na.rm=TRUE),
    wds_corp_ins_54_sum        = sum(wds_corp_ins_54        , na.rm=TRUE),
    wds_corp_ins_55_sum        = sum(wds_corp_ins_55        , na.rm=TRUE),
    wds_corp_ins_56_sum        = sum(wds_corp_ins_56        , na.rm=TRUE),
    wds_corp_ins_112_sum       = sum(wds_corp_ins_112       , na.rm=TRUE),
    wds_corp_ins_113_sum       = sum(wds_corp_ins_113       , na.rm=TRUE),
    wds_corp_ins_123_sum       = sum(wds_corp_ins_123       , na.rm=TRUE),
    wds_corp_ins_131_sum       = sum(wds_corp_ins_131       , na.rm=TRUE),
    wds_corp_ins_142_sum       = sum(wds_corp_ins_142       , na.rm=TRUE),
    wds_corp_ins_411_sum       = sum(wds_corp_ins_411       , na.rm=TRUE),
    wds_corp_ins_611_sum       = sum(wds_corp_ins_611       , na.rm=TRUE),
    wds_corp_ins_636_sum       = sum(wds_corp_ins_636       , na.rm=TRUE),
    wds_corp_ins_638_sum       = sum(wds_corp_ins_638       , na.rm=TRUE),
    wds_corp_ins_652_sum       = sum(wds_corp_ins_652       , na.rm=TRUE),
    wds_corp_ins_6212_sum      = sum(wds_corp_ins_6212      , na.rm=TRUE),
    wds_corp_ins_145_sum       = sum(wds_corp_ins_145       , na.rm=TRUE),
    wds_corp_ins_22_sum        = sum(wds_corp_ins_22        , na.rm=TRUE),
    wds_corp_ins_23_sum        = sum(wds_corp_ins_23        , na.rm=TRUE),
    wds_corp_ins_43_sum        = sum(wds_corp_ins_43        , na.rm=TRUE),
    wds_corp_ins_134_sum       = sum(wds_corp_ins_134       , na.rm=TRUE),
    wds_corp_ins_612_sum       = sum(wds_corp_ins_612       , na.rm=TRUE),
    wds_corp_ins_241_sum       = sum(wds_corp_ins_241       , na.rm=TRUE),
    wds_corp_ins_243_sum       = sum(wds_corp_ins_243       , na.rm=TRUE),
    wds_corp_ins_72_sum        = sum(wds_corp_ins_72        , na.rm=TRUE),
    wds_corp_ins_114_sum       = sum(wds_corp_ins_114       , na.rm=TRUE),
    wds_corp_ins_242_sum       = sum(wds_corp_ins_242       , na.rm=TRUE),
    wds_corp_ins_244_sum       = sum(wds_corp_ins_244       , na.rm=TRUE),
    wds_corp_ins_631_sum       = sum(wds_corp_ins_631       , na.rm=TRUE),
    wds_corp_ins_639_sum       = sum(wds_corp_ins_639       , na.rm=TRUE),
    wds_corp_ins_642_sum       = sum(wds_corp_ins_642       , na.rm=TRUE),
    wds_corp_ins_6352_sum      = sum(wds_corp_ins_6352      , na.rm=TRUE),
    wds_corp_ins_68_sum        = sum(wds_corp_ins_68        , na.rm=TRUE),
    wds_corp_ins_29_sum        = sum(wds_corp_ins_29        , na.rm=TRUE),
    wds_corp_ins_122_sum       = sum(wds_corp_ins_122       , na.rm=TRUE),
    wds_corp_ins_133_sum       = sum(wds_corp_ins_133       , na.rm=TRUE),
    wds_corp_ins_643_sum       = sum(wds_corp_ins_643       , na.rm=TRUE),
    wds_corp_ins_124_sum       = sum(wds_corp_ins_124       , na.rm=TRUE),
    wds_corp_ins_613_sum       = sum(wds_corp_ins_613       , na.rm=TRUE),
    wds_corp_ins_33_sum        = sum(wds_corp_ins_33        , na.rm=TRUE),
    wds_corp_ins_71_sum        = sum(wds_corp_ins_71        , na.rm=TRUE),
    wds_corp_ins_132_sum       = sum(wds_corp_ins_132       , na.rm=TRUE),
    wds_corp_ins_143_sum       = sum(wds_corp_ins_143       , na.rm=TRUE),
    wds_corp_ins_27_sum        = sum(wds_corp_ins_27        , na.rm=TRUE),
    wds_corp_ins_28_sum        = sum(wds_corp_ins_28        , na.rm=TRUE),
    wds_corp_ins_31_sum        = sum(wds_corp_ins_31        , na.rm=TRUE),
    wds_corp_ins_653_sum       = sum(wds_corp_ins_653       , na.rm=TRUE),
    wds_corp_ins_66_sum        = sum(wds_corp_ins_66        , na.rm=TRUE),
    wds_corp_ins_442_sum       = sum(wds_corp_ins_442       , na.rm=TRUE),
    wds_corp_ins_441_sum       = sum(wds_corp_ins_441       , na.rm=TRUE),
    wds_corp_ins_141_sum       = sum(wds_corp_ins_141       , na.rm=TRUE),
    wds_corp_ins_73_sum        = sum(wds_corp_ins_73        , na.rm=TRUE),
    wds_corp_ins_6351_sum      = sum(wds_corp_ins_6351      , na.rm=TRUE),
    wds_corp_ins_45_sum        = sum(wds_corp_ins_45        , na.rm=TRUE),
    wds_corp_ins_144_sum       = sum(wds_corp_ins_144       , na.rm=TRUE),
    wds_corp_ins_422_sum       = sum(wds_corp_ins_422       , na.rm=TRUE),
    wds_corp_ins_67_sum        = sum(wds_corp_ins_67        , na.rm=TRUE),
    wds_corp_ins_421_sum       = sum(wds_corp_ins_421       , na.rm=TRUE),
    wds_corp_del_9_sum         = sum(wds_corp_del_9         , na.rm=TRUE),
    wds_corp_del_51_sum        = sum(wds_corp_del_51        , na.rm=TRUE),
    wds_corp_del_71_sum        = sum(wds_corp_del_71        , na.rm=TRUE),
    wds_corp_del_121_sum       = sum(wds_corp_del_121       , na.rm=TRUE),
    wds_corp_del_651_sum       = sum(wds_corp_del_651       , na.rm=TRUE),
    wds_corp_del_22_sum        = sum(wds_corp_del_22        , na.rm=TRUE),
    wds_corp_del_23_sum        = sum(wds_corp_del_23        , na.rm=TRUE),
    wds_corp_del_25_sum        = sum(wds_corp_del_25        , na.rm=TRUE),
    wds_corp_del_34_sum        = sum(wds_corp_del_34        , na.rm=TRUE),
    wds_corp_del_53_sum        = sum(wds_corp_del_53        , na.rm=TRUE),
    wds_corp_del_54_sum        = sum(wds_corp_del_54        , na.rm=TRUE),
    wds_corp_del_55_sum        = sum(wds_corp_del_55        , na.rm=TRUE),
    wds_corp_del_56_sum        = sum(wds_corp_del_56        , na.rm=TRUE),
    wds_corp_del_111_sum       = sum(wds_corp_del_111       , na.rm=TRUE),
    wds_corp_del_123_sum       = sum(wds_corp_del_123       , na.rm=TRUE),
    wds_corp_del_142_sum       = sum(wds_corp_del_142       , na.rm=TRUE),
    wds_corp_del_143_sum       = sum(wds_corp_del_143       , na.rm=TRUE),
    wds_corp_del_611_sum       = sum(wds_corp_del_611       , na.rm=TRUE),
    wds_corp_del_612_sum       = sum(wds_corp_del_612       , na.rm=TRUE),
    wds_corp_del_633_sum       = sum(wds_corp_del_633       , na.rm=TRUE),
    wds_corp_del_634_sum       = sum(wds_corp_del_634       , na.rm=TRUE),
    wds_corp_del_652_sum       = sum(wds_corp_del_652       , na.rm=TRUE),
    wds_corp_del_6211_sum      = sum(wds_corp_del_6211      , na.rm=TRUE),
    wds_corp_del_6212_sum      = sum(wds_corp_del_6212      , na.rm=TRUE),
    wds_corp_del_6351_sum      = sum(wds_corp_del_6351      , na.rm=TRUE),
    wds_corp_del_113_sum       = sum(wds_corp_del_113       , na.rm=TRUE),
    wds_corp_del_637_sum       = sum(wds_corp_del_637       , na.rm=TRUE),
    wds_corp_del_52_sum        = sum(wds_corp_del_52        , na.rm=TRUE),
    wds_corp_del_241_sum       = sum(wds_corp_del_241       , na.rm=TRUE),
    wds_corp_del_243_sum       = sum(wds_corp_del_243       , na.rm=TRUE),
    wds_corp_del_26_sum        = sum(wds_corp_del_26        , na.rm=TRUE),
    wds_corp_del_632_sum       = sum(wds_corp_del_632       , na.rm=TRUE),
    wds_corp_del_10_sum        = sum(wds_corp_del_10        , na.rm=TRUE),
    wds_corp_del_112_sum       = sum(wds_corp_del_112       , na.rm=TRUE),
    wds_corp_del_114_sum       = sum(wds_corp_del_114       , na.rm=TRUE),
    wds_corp_del_122_sum       = sum(wds_corp_del_122       , na.rm=TRUE),
    wds_corp_del_125_sum       = sum(wds_corp_del_125       , na.rm=TRUE),
    wds_corp_del_132_sum       = sum(wds_corp_del_132       , na.rm=TRUE),
    wds_corp_del_613_sum       = sum(wds_corp_del_613       , na.rm=TRUE),
    wds_corp_del_631_sum       = sum(wds_corp_del_631       , na.rm=TRUE),
    wds_corp_del_639_sum       = sum(wds_corp_del_639       , na.rm=TRUE),
    wds_corp_del_242_sum       = sum(wds_corp_del_242       , na.rm=TRUE),
    wds_corp_del_68_sum        = sum(wds_corp_del_68        , na.rm=TRUE),
    wds_corp_del_134_sum       = sum(wds_corp_del_134       , na.rm=TRUE),
    wds_corp_del_72_sum        = sum(wds_corp_del_72        , na.rm=TRUE),
    wds_corp_del_999_sum       = sum(wds_corp_del_999       , na.rm=TRUE),
    wds_corp_del_131_sum       = sum(wds_corp_del_131       , na.rm=TRUE),
    wds_corp_del_124_sum       = sum(wds_corp_del_124       , na.rm=TRUE),
    wds_corp_del_636_sum       = sum(wds_corp_del_636       , na.rm=TRUE),
    wds_corp_del_21_sum        = sum(wds_corp_del_21        , na.rm=TRUE),
    wds_corp_del_29_sum        = sum(wds_corp_del_29        , na.rm=TRUE),
    wds_corp_del_642_sum       = sum(wds_corp_del_642       , na.rm=TRUE),
    wds_corp_del_8_sum         = sum(wds_corp_del_8         , na.rm=TRUE),
    wds_corp_del_32_sum        = sum(wds_corp_del_32        , na.rm=TRUE),
    wds_corp_del_33_sum        = sum(wds_corp_del_33        , na.rm=TRUE),
    wds_corp_del_43_sum        = sum(wds_corp_del_43        , na.rm=TRUE),
    wds_corp_del_133_sum       = sum(wds_corp_del_133       , na.rm=TRUE),
    wds_corp_del_641_sum       = sum(wds_corp_del_641       , na.rm=TRUE),
    wds_corp_del_653_sum       = sum(wds_corp_del_653       , na.rm=TRUE),
    wds_corp_del_244_sum       = sum(wds_corp_del_244       , na.rm=TRUE),
    wds_corp_del_6221_sum      = sum(wds_corp_del_6221      , na.rm=TRUE),
    wds_corp_del_6222_sum      = sum(wds_corp_del_6222      , na.rm=TRUE),
    wds_corp_del_441_sum       = sum(wds_corp_del_441       , na.rm=TRUE),
    wds_corp_del_6352_sum      = sum(wds_corp_del_6352      , na.rm=TRUE),
    wds_corp_del_73_sum        = sum(wds_corp_del_73        , na.rm=TRUE),
    wds_corp_del_638_sum       = sum(wds_corp_del_638       , na.rm=TRUE),
    wds_corp_del_45_sum        = sum(wds_corp_del_45        , na.rm=TRUE),
    wds_corp_del_411_sum       = sum(wds_corp_del_411       , na.rm=TRUE),
    wds_corp_del_412_sum       = sum(wds_corp_del_412       , na.rm=TRUE),
    wds_corp_del_27_sum        = sum(wds_corp_del_27        , na.rm=TRUE),
    wds_corp_del_643_sum       = sum(wds_corp_del_643       , na.rm=TRUE),
    wds_corp_del_28_sum        = sum(wds_corp_del_28        , na.rm=TRUE),
    wds_corp_del_31_sum        = sum(wds_corp_del_31        , na.rm=TRUE),
    wds_corp_del_421_sum       = sum(wds_corp_del_421       , na.rm=TRUE),
    wds_corp_del_422_sum       = sum(wds_corp_del_422       , na.rm=TRUE),
    wds_corp_del_141_sum       = sum(wds_corp_del_141       , na.rm=TRUE),
    wds_corp_del_144_sum       = sum(wds_corp_del_144       , na.rm=TRUE),
    
    lang                   = first(lang),
    wdns                   = first(wdns),
    wdns_corr              = first(wdns_corr),
    
    wds_clean_rel_wdns_corr_fst = first(wds_clean_rel_wdns_corr),
    wds_clean_rel_wdns_corr_lst = last(wds_clean_rel_wdns_corr),
    wds_clean_rel_wdns_corr_mn  = mean(wds_clean_rel_wdns_corr  , na.rm=TRUE),
    
    t_date_lag             = first(t_date_lag),
    t_date_lead            = first(t_date_lead),
    t_snc_lst_ref          = first(t_snc_lst_ref),
    t_to_nxt_ref           = first(t_to_nxt_ref),
    
    t_date_lag_mn          = mean(t_date_lag),
    t_date_lead_mn         = mean(t_date_lead),
    t_snc_lst_ref_mn       = mean(t_snc_lst_ref),
    t_to_nxt_ref_mn        = mean(t_to_nxt_ref),
    
    t_date_lag_lst         = last(t_date_lag),
    t_date_lead_lst        = last(t_date_lead),
    t_snc_lst_ref_lst      = last(t_snc_lst_ref),
    t_to_nxt_ref_lst       = last(t_to_nxt_ref),
    
    lns_corp_mdf_8_sum      = sum(lns_corp_mdf_8         , na.rm=TRUE),
    lns_corp_ins_8_sum      = sum(lns_corp_ins_8         , na.rm=TRUE),
    lns_corp_del_8_sum      = sum(lns_corp_del_8         , na.rm=TRUE),
    lns_corp_mdf_9_sum      = sum(lns_corp_mdf_9         , na.rm=TRUE),
    lns_corp_ins_9_sum      = sum(lns_corp_ins_9         , na.rm=TRUE),
    lns_corp_del_9_sum      = sum(lns_corp_del_9         , na.rm=TRUE),
    lns_corp_mdf_10_sum     = sum(lns_corp_mdf_10        , na.rm=TRUE),
    lns_corp_ins_10_sum     = sum(lns_corp_ins_10        , na.rm=TRUE),
    lns_corp_del_10_sum     = sum(lns_corp_del_10        , na.rm=TRUE),
    lns_corp_mdf_21_sum     = sum(lns_corp_mdf_21        , na.rm=TRUE),
    lns_corp_ins_21_sum     = sum(lns_corp_ins_21        , na.rm=TRUE),
    lns_corp_del_21_sum     = sum(lns_corp_del_21        , na.rm=TRUE),
    lns_corp_mdf_22_sum     = sum(lns_corp_mdf_22        , na.rm=TRUE),
    lns_corp_ins_22_sum     = sum(lns_corp_ins_22        , na.rm=TRUE),
    lns_corp_del_22_sum     = sum(lns_corp_del_22        , na.rm=TRUE),
    lns_corp_mdf_23_sum     = sum(lns_corp_mdf_23        , na.rm=TRUE),
    lns_corp_ins_23_sum     = sum(lns_corp_ins_23        , na.rm=TRUE),
    lns_corp_del_23_sum     = sum(lns_corp_del_23        , na.rm=TRUE),
    lns_corp_mdf_25_sum     = sum(lns_corp_mdf_25        , na.rm=TRUE),
    lns_corp_ins_25_sum     = sum(lns_corp_ins_25        , na.rm=TRUE),
    lns_corp_del_25_sum     = sum(lns_corp_del_25        , na.rm=TRUE),
    lns_corp_mdf_26_sum     = sum(lns_corp_mdf_26        , na.rm=TRUE),
    lns_corp_ins_26_sum     = sum(lns_corp_ins_26        , na.rm=TRUE),
    lns_corp_del_26_sum     = sum(lns_corp_del_26        , na.rm=TRUE),
    lns_corp_mdf_27_sum     = sum(lns_corp_mdf_27        , na.rm=TRUE),
    lns_corp_ins_27_sum     = sum(lns_corp_ins_27        , na.rm=TRUE),
    lns_corp_del_27_sum     = sum(lns_corp_del_27        , na.rm=TRUE),
    lns_corp_mdf_28_sum     = sum(lns_corp_mdf_28        , na.rm=TRUE),
    lns_corp_ins_28_sum     = sum(lns_corp_ins_28        , na.rm=TRUE),
    lns_corp_del_28_sum     = sum(lns_corp_del_28        , na.rm=TRUE),
    lns_corp_mdf_29_sum     = sum(lns_corp_mdf_29        , na.rm=TRUE),
    lns_corp_ins_29_sum     = sum(lns_corp_ins_29        , na.rm=TRUE),
    lns_corp_del_29_sum     = sum(lns_corp_del_29        , na.rm=TRUE),
    lns_corp_mdf_31_sum     = sum(lns_corp_mdf_31        , na.rm=TRUE),
    lns_corp_ins_31_sum     = sum(lns_corp_ins_31        , na.rm=TRUE),
    lns_corp_del_31_sum     = sum(lns_corp_del_31        , na.rm=TRUE),
    lns_corp_mdf_32_sum     = sum(lns_corp_mdf_32        , na.rm=TRUE),
    lns_corp_ins_32_sum     = sum(lns_corp_ins_32        , na.rm=TRUE),
    lns_corp_del_32_sum     = sum(lns_corp_del_32        , na.rm=TRUE),
    lns_corp_mdf_33_sum     = sum(lns_corp_mdf_33        , na.rm=TRUE),
    lns_corp_ins_33_sum     = sum(lns_corp_ins_33        , na.rm=TRUE),
    lns_corp_del_33_sum     = sum(lns_corp_del_33        , na.rm=TRUE),
    lns_corp_mdf_34_sum     = sum(lns_corp_mdf_34        , na.rm=TRUE),
    lns_corp_ins_34_sum     = sum(lns_corp_ins_34        , na.rm=TRUE),
    lns_corp_del_34_sum     = sum(lns_corp_del_34        , na.rm=TRUE),
    lns_corp_mdf_43_sum     = sum(lns_corp_mdf_43        , na.rm=TRUE),
    lns_corp_ins_43_sum     = sum(lns_corp_ins_43        , na.rm=TRUE),
    lns_corp_del_43_sum     = sum(lns_corp_del_43        , na.rm=TRUE),
    lns_corp_mdf_45_sum     = sum(lns_corp_mdf_45        , na.rm=TRUE),
    lns_corp_ins_45_sum     = sum(lns_corp_ins_45        , na.rm=TRUE),
    lns_corp_del_45_sum     = sum(lns_corp_del_45        , na.rm=TRUE),
    lns_corp_mdf_51_sum     = sum(lns_corp_mdf_51        , na.rm=TRUE),
    lns_corp_ins_51_sum     = sum(lns_corp_ins_51        , na.rm=TRUE),
    lns_corp_del_51_sum     = sum(lns_corp_del_51        , na.rm=TRUE),
    lns_corp_mdf_52_sum     = sum(lns_corp_mdf_52        , na.rm=TRUE),
    lns_corp_ins_52_sum     = sum(lns_corp_ins_52        , na.rm=TRUE),
    lns_corp_del_52_sum     = sum(lns_corp_del_52        , na.rm=TRUE),
    lns_corp_mdf_53_sum     = sum(lns_corp_mdf_53        , na.rm=TRUE),
    lns_corp_ins_53_sum     = sum(lns_corp_ins_53        , na.rm=TRUE),
    lns_corp_del_53_sum     = sum(lns_corp_del_53        , na.rm=TRUE),
    lns_corp_mdf_54_sum     = sum(lns_corp_mdf_54        , na.rm=TRUE),
    lns_corp_ins_54_sum     = sum(lns_corp_ins_54        , na.rm=TRUE),
    lns_corp_del_54_sum     = sum(lns_corp_del_54        , na.rm=TRUE),
    lns_corp_mdf_55_sum     = sum(lns_corp_mdf_55        , na.rm=TRUE),
    lns_corp_ins_55_sum     = sum(lns_corp_ins_55        , na.rm=TRUE),
    lns_corp_del_55_sum     = sum(lns_corp_del_55        , na.rm=TRUE),
    lns_corp_mdf_56_sum     = sum(lns_corp_mdf_56        , na.rm=TRUE),
    lns_corp_ins_56_sum     = sum(lns_corp_ins_56        , na.rm=TRUE),
    lns_corp_del_56_sum     = sum(lns_corp_del_56        , na.rm=TRUE),
    wds_corp_mdf_66_sum     = sum(wds_corp_mdf_66        , na.rm=TRUE),
    wds_corp_del_66_sum     = sum(wds_corp_del_66        , na.rm=TRUE),
    lns_corp_mdf_66_sum     = sum(lns_corp_mdf_66        , na.rm=TRUE),
    lns_corp_ins_66_sum     = sum(lns_corp_ins_66        , na.rm=TRUE),
    lns_corp_del_66_sum     = sum(lns_corp_del_66        , na.rm=TRUE),
    wds_corp_del_67_sum     = sum(wds_corp_del_67        , na.rm=TRUE),
    lns_corp_mdf_67_sum     = sum(lns_corp_mdf_67        , na.rm=TRUE),
    lns_corp_ins_67_sum     = sum(lns_corp_ins_67        , na.rm=TRUE),
    lns_corp_del_67_sum     = sum(lns_corp_del_67        , na.rm=TRUE),
    lns_corp_mdf_68_sum     = sum(lns_corp_mdf_68        , na.rm=TRUE),
    lns_corp_ins_68_sum     = sum(lns_corp_ins_68        , na.rm=TRUE),
    lns_corp_del_68_sum     = sum(lns_corp_del_68        , na.rm=TRUE),
    lns_corp_mdf_71_sum     = sum(lns_corp_mdf_71        , na.rm=TRUE),
    lns_corp_ins_71_sum     = sum(lns_corp_ins_71        , na.rm=TRUE),
    lns_corp_del_71_sum     = sum(lns_corp_del_71        , na.rm=TRUE),
    lns_corp_mdf_72_sum     = sum(lns_corp_mdf_72        , na.rm=TRUE),
    lns_corp_ins_72_sum     = sum(lns_corp_ins_72        , na.rm=TRUE),
    lns_corp_del_72_sum     = sum(lns_corp_del_72        , na.rm=TRUE),
    lns_corp_mdf_73_sum     = sum(lns_corp_mdf_73        , na.rm=TRUE),
    lns_corp_ins_73_sum     = sum(lns_corp_ins_73        , na.rm=TRUE),
    lns_corp_del_73_sum     = sum(lns_corp_del_73        , na.rm=TRUE),
    lns_corp_mdf_111_sum    = sum(lns_corp_mdf_111       , na.rm=TRUE),
    lns_corp_ins_111_sum    = sum(lns_corp_ins_111       , na.rm=TRUE),
    lns_corp_del_111_sum    = sum(lns_corp_del_111       , na.rm=TRUE),
    lns_corp_mdf_112_sum    = sum(lns_corp_mdf_112       , na.rm=TRUE),
    lns_corp_ins_112_sum    = sum(lns_corp_ins_112       , na.rm=TRUE),
    lns_corp_del_112_sum    = sum(lns_corp_del_112       , na.rm=TRUE),
    lns_corp_mdf_113_sum    = sum(lns_corp_mdf_113       , na.rm=TRUE),
    lns_corp_ins_113_sum    = sum(lns_corp_ins_113       , na.rm=TRUE),
    lns_corp_del_113_sum    = sum(lns_corp_del_113       , na.rm=TRUE),
    lns_corp_mdf_114_sum    = sum(lns_corp_mdf_114       , na.rm=TRUE),
    lns_corp_ins_114_sum    = sum(lns_corp_ins_114       , na.rm=TRUE),
    lns_corp_del_114_sum    = sum(lns_corp_del_114       , na.rm=TRUE),
    lns_corp_mdf_121_sum    = sum(lns_corp_mdf_121       , na.rm=TRUE),
    lns_corp_ins_121_sum    = sum(lns_corp_ins_121       , na.rm=TRUE),
    lns_corp_del_121_sum    = sum(lns_corp_del_121       , na.rm=TRUE),
    lns_corp_mdf_122_sum    = sum(lns_corp_mdf_122       , na.rm=TRUE),
    lns_corp_ins_122_sum    = sum(lns_corp_ins_122       , na.rm=TRUE),
    lns_corp_del_122_sum    = sum(lns_corp_del_122       , na.rm=TRUE),
    lns_corp_mdf_123_sum    = sum(lns_corp_mdf_123       , na.rm=TRUE),
    lns_corp_ins_123_sum    = sum(lns_corp_ins_123       , na.rm=TRUE),
    lns_corp_del_123_sum    = sum(lns_corp_del_123       , na.rm=TRUE),
    lns_corp_mdf_124_sum    = sum(lns_corp_mdf_124       , na.rm=TRUE),
    lns_corp_ins_124_sum    = sum(lns_corp_ins_124       , na.rm=TRUE),
    lns_corp_del_124_sum    = sum(lns_corp_del_124       , na.rm=TRUE),
    lns_corp_mdf_125_sum    = sum(lns_corp_mdf_125       , na.rm=TRUE),
    lns_corp_ins_125_sum    = sum(lns_corp_ins_125       , na.rm=TRUE),
    lns_corp_del_125_sum    = sum(lns_corp_del_125       , na.rm=TRUE),
    lns_corp_mdf_131_sum    = sum(lns_corp_mdf_131       , na.rm=TRUE),
    lns_corp_ins_131_sum    = sum(lns_corp_ins_131       , na.rm=TRUE),
    lns_corp_del_131_sum    = sum(lns_corp_del_131       , na.rm=TRUE),
    lns_corp_mdf_132_sum    = sum(lns_corp_mdf_132       , na.rm=TRUE),
    lns_corp_ins_132_sum    = sum(lns_corp_ins_132       , na.rm=TRUE),
    lns_corp_del_132_sum    = sum(lns_corp_del_132       , na.rm=TRUE),
    lns_corp_mdf_133_sum    = sum(lns_corp_mdf_133       , na.rm=TRUE),
    lns_corp_ins_133_sum    = sum(lns_corp_ins_133       , na.rm=TRUE),
    lns_corp_del_133_sum    = sum(lns_corp_del_133       , na.rm=TRUE),
    lns_corp_mdf_134_sum    = sum(lns_corp_mdf_134       , na.rm=TRUE),
    lns_corp_ins_134_sum    = sum(lns_corp_ins_134       , na.rm=TRUE),
    lns_corp_del_134_sum    = sum(lns_corp_del_134       , na.rm=TRUE),
    lns_corp_mdf_141_sum    = sum(lns_corp_mdf_141       , na.rm=TRUE),
    lns_corp_ins_141_sum    = sum(lns_corp_ins_141       , na.rm=TRUE),
    lns_corp_del_141_sum    = sum(lns_corp_del_141       , na.rm=TRUE),
    lns_corp_mdf_142_sum    = sum(lns_corp_mdf_142       , na.rm=TRUE),
    lns_corp_ins_142_sum    = sum(lns_corp_ins_142       , na.rm=TRUE),
    lns_corp_del_142_sum    = sum(lns_corp_del_142       , na.rm=TRUE),
    lns_corp_mdf_143_sum    = sum(lns_corp_mdf_143       , na.rm=TRUE),
    lns_corp_ins_143_sum    = sum(lns_corp_ins_143       , na.rm=TRUE),
    lns_corp_del_143_sum    = sum(lns_corp_del_143       , na.rm=TRUE),
    lns_corp_mdf_144_sum    = sum(lns_corp_mdf_144       , na.rm=TRUE),
    lns_corp_ins_144_sum    = sum(lns_corp_ins_144       , na.rm=TRUE),
    lns_corp_del_144_sum    = sum(lns_corp_del_144       , na.rm=TRUE),
    wds_corp_del_145_sum    = sum(wds_corp_del_145       , na.rm=TRUE),
    lns_corp_mdf_145_sum    = sum(lns_corp_mdf_145       , na.rm=TRUE),
    lns_corp_ins_145_sum    = sum(lns_corp_ins_145       , na.rm=TRUE),
    lns_corp_del_145_sum    = sum(lns_corp_del_145       , na.rm=TRUE),
    lns_corp_mdf_241_sum    = sum(lns_corp_mdf_241       , na.rm=TRUE),
    lns_corp_ins_241_sum    = sum(lns_corp_ins_241       , na.rm=TRUE),
    lns_corp_del_241_sum    = sum(lns_corp_del_241       , na.rm=TRUE),
    lns_corp_mdf_242_sum    = sum(lns_corp_mdf_242       , na.rm=TRUE),
    lns_corp_ins_242_sum    = sum(lns_corp_ins_242       , na.rm=TRUE),
    lns_corp_del_242_sum    = sum(lns_corp_del_242       , na.rm=TRUE),
    lns_corp_mdf_243_sum    = sum(lns_corp_mdf_243       , na.rm=TRUE),
    lns_corp_ins_243_sum    = sum(lns_corp_ins_243       , na.rm=TRUE),
    lns_corp_del_243_sum    = sum(lns_corp_del_243       , na.rm=TRUE),
    lns_corp_mdf_244_sum    = sum(lns_corp_mdf_244       , na.rm=TRUE),
    lns_corp_ins_244_sum    = sum(lns_corp_ins_244       , na.rm=TRUE),
    lns_corp_del_244_sum    = sum(lns_corp_del_244       , na.rm=TRUE),
    lns_corp_mdf_411_sum    = sum(lns_corp_mdf_411       , na.rm=TRUE),
    lns_corp_ins_411_sum    = sum(lns_corp_ins_411       , na.rm=TRUE),
    lns_corp_del_411_sum    = sum(lns_corp_del_411       , na.rm=TRUE),
    lns_corp_mdf_412_sum    = sum(lns_corp_mdf_412       , na.rm=TRUE),
    lns_corp_ins_412_sum    = sum(lns_corp_ins_412       , na.rm=TRUE),
    lns_corp_del_412_sum    = sum(lns_corp_del_412       , na.rm=TRUE),
    lns_corp_mdf_421_sum    = sum(lns_corp_mdf_421       , na.rm=TRUE),
    lns_corp_ins_421_sum    = sum(lns_corp_ins_421       , na.rm=TRUE),
    lns_corp_del_421_sum    = sum(lns_corp_del_421       , na.rm=TRUE),
    lns_corp_mdf_422_sum    = sum(lns_corp_mdf_422       , na.rm=TRUE),
    lns_corp_ins_422_sum    = sum(lns_corp_ins_422       , na.rm=TRUE),
    lns_corp_del_422_sum    = sum(lns_corp_del_422       , na.rm=TRUE),
    wds_corp_mdf_441_sum    = sum(wds_corp_mdf_441       , na.rm=TRUE),
    lns_corp_mdf_441_sum    = sum(lns_corp_mdf_441       , na.rm=TRUE),
    lns_corp_ins_441_sum    = sum(lns_corp_ins_441       , na.rm=TRUE),
    lns_corp_del_441_sum    = sum(lns_corp_del_441       , na.rm=TRUE),
    wds_corp_del_442_sum    = sum(wds_corp_del_442       , na.rm=TRUE),
    lns_corp_mdf_442_sum    = sum(lns_corp_mdf_442       , na.rm=TRUE),
    lns_corp_ins_442_sum    = sum(lns_corp_ins_442       , na.rm=TRUE),
    lns_corp_del_442_sum    = sum(lns_corp_del_442       , na.rm=TRUE),
    lns_corp_mdf_611_sum    = sum(lns_corp_mdf_611       , na.rm=TRUE),
    lns_corp_ins_611_sum    = sum(lns_corp_ins_611       , na.rm=TRUE),
    lns_corp_del_611_sum    = sum(lns_corp_del_611       , na.rm=TRUE),
    lns_corp_mdf_612_sum    = sum(lns_corp_mdf_612       , na.rm=TRUE),
    lns_corp_ins_612_sum    = sum(lns_corp_ins_612       , na.rm=TRUE),
    lns_corp_del_612_sum    = sum(lns_corp_del_612       , na.rm=TRUE),
    lns_corp_mdf_613_sum    = sum(lns_corp_mdf_613       , na.rm=TRUE),
    lns_corp_ins_613_sum    = sum(lns_corp_ins_613       , na.rm=TRUE),
    lns_corp_del_613_sum    = sum(lns_corp_del_613       , na.rm=TRUE),
    lns_corp_mdf_631_sum    = sum(lns_corp_mdf_631       , na.rm=TRUE),
    lns_corp_ins_631_sum    = sum(lns_corp_ins_631       , na.rm=TRUE),
    lns_corp_del_631_sum    = sum(lns_corp_del_631       , na.rm=TRUE),
    lns_corp_mdf_632_sum    = sum(lns_corp_mdf_632       , na.rm=TRUE),
    lns_corp_ins_632_sum    = sum(lns_corp_ins_632       , na.rm=TRUE),
    lns_corp_del_632_sum    = sum(lns_corp_del_632       , na.rm=TRUE),
    lns_corp_mdf_633_sum    = sum(lns_corp_mdf_633       , na.rm=TRUE),
    lns_corp_ins_633_sum    = sum(lns_corp_ins_633       , na.rm=TRUE),
    lns_corp_del_633_sum    = sum(lns_corp_del_633       , na.rm=TRUE),
    lns_corp_mdf_634_sum    = sum(lns_corp_mdf_634       , na.rm=TRUE),
    lns_corp_ins_634_sum    = sum(lns_corp_ins_634       , na.rm=TRUE),
    lns_corp_del_634_sum    = sum(lns_corp_del_634       , na.rm=TRUE),
    lns_corp_mdf_636_sum    = sum(lns_corp_mdf_636       , na.rm=TRUE),
    lns_corp_ins_636_sum    = sum(lns_corp_ins_636       , na.rm=TRUE),
    lns_corp_del_636_sum    = sum(lns_corp_del_636       , na.rm=TRUE),
    lns_corp_mdf_637_sum    = sum(lns_corp_mdf_637       , na.rm=TRUE),
    lns_corp_ins_637_sum    = sum(lns_corp_ins_637       , na.rm=TRUE),
    lns_corp_del_637_sum    = sum(lns_corp_del_637       , na.rm=TRUE),
    lns_corp_mdf_638_sum    = sum(lns_corp_mdf_638       , na.rm=TRUE),
    lns_corp_ins_638_sum    = sum(lns_corp_ins_638       , na.rm=TRUE),
    lns_corp_del_638_sum    = sum(lns_corp_del_638       , na.rm=TRUE),
    lns_corp_mdf_639_sum    = sum(lns_corp_mdf_639       , na.rm=TRUE),
    lns_corp_ins_639_sum    = sum(lns_corp_ins_639       , na.rm=TRUE),
    lns_corp_del_639_sum    = sum(lns_corp_del_639       , na.rm=TRUE),
    lns_corp_mdf_641_sum    = sum(lns_corp_mdf_641       , na.rm=TRUE),
    lns_corp_ins_641_sum    = sum(lns_corp_ins_641       , na.rm=TRUE),
    lns_corp_del_641_sum    = sum(lns_corp_del_641       , na.rm=TRUE),
    lns_corp_mdf_642_sum    = sum(lns_corp_mdf_642       , na.rm=TRUE),
    lns_corp_ins_642_sum    = sum(lns_corp_ins_642       , na.rm=TRUE),
    lns_corp_del_642_sum    = sum(lns_corp_del_642       , na.rm=TRUE),
    lns_corp_mdf_643_sum    = sum(lns_corp_mdf_643       , na.rm=TRUE),
    lns_corp_ins_643_sum    = sum(lns_corp_ins_643       , na.rm=TRUE),
    lns_corp_del_643_sum    = sum(lns_corp_del_643       , na.rm=TRUE),
    lns_corp_mdf_651_sum    = sum(lns_corp_mdf_651       , na.rm=TRUE),
    lns_corp_ins_651_sum    = sum(lns_corp_ins_651       , na.rm=TRUE),
    lns_corp_del_651_sum    = sum(lns_corp_del_651       , na.rm=TRUE),
    lns_corp_mdf_652_sum    = sum(lns_corp_mdf_652       , na.rm=TRUE),
    lns_corp_ins_652_sum    = sum(lns_corp_ins_652       , na.rm=TRUE),
    lns_corp_del_652_sum    = sum(lns_corp_del_652       , na.rm=TRUE),
    lns_corp_mdf_653_sum    = sum(lns_corp_mdf_653       , na.rm=TRUE),
    lns_corp_ins_653_sum    = sum(lns_corp_ins_653       , na.rm=TRUE),
    lns_corp_del_653_sum    = sum(lns_corp_del_653       , na.rm=TRUE),
    wds_corp_mdf_999_sum    = sum(wds_corp_mdf_999       , na.rm=TRUE),
    wds_corp_ins_999_sum    = sum(wds_corp_ins_999       , na.rm=TRUE),
    lns_corp_mdf_999_sum    = sum(lns_corp_mdf_999       , na.rm=TRUE),
    lns_corp_ins_999_sum    = sum(lns_corp_ins_999       , na.rm=TRUE),
    lns_corp_del_999_sum    = sum(lns_corp_del_999       , na.rm=TRUE),
    lns_corp_mdf_6211_sum   = sum(lns_corp_mdf_6211      , na.rm=TRUE),
    lns_corp_ins_6211_sum   = sum(lns_corp_ins_6211      , na.rm=TRUE),
    lns_corp_del_6211_sum   = sum(lns_corp_del_6211      , na.rm=TRUE),
    lns_corp_mdf_6212_sum   = sum(lns_corp_mdf_6212      , na.rm=TRUE),
    lns_corp_ins_6212_sum   = sum(lns_corp_ins_6212      , na.rm=TRUE),
    lns_corp_del_6212_sum   = sum(lns_corp_del_6212      , na.rm=TRUE),
    lns_corp_mdf_6221_sum   = sum(lns_corp_mdf_6221      , na.rm=TRUE),
    lns_corp_ins_6221_sum   = sum(lns_corp_ins_6221      , na.rm=TRUE),
    lns_corp_del_6221_sum   = sum(lns_corp_del_6221      , na.rm=TRUE),
    lns_corp_mdf_6222_sum   = sum(lns_corp_mdf_6222      , na.rm=TRUE),
    lns_corp_ins_6222_sum   = sum(lns_corp_ins_6222      , na.rm=TRUE),
    lns_corp_del_6222_sum   = sum(lns_corp_del_6222      , na.rm=TRUE),
    lns_corp_mdf_6351_sum   = sum(lns_corp_mdf_6351      , na.rm=TRUE),
    lns_corp_ins_6351_sum   = sum(lns_corp_ins_6351      , na.rm=TRUE),
    lns_corp_del_6351_sum   = sum(lns_corp_del_6351      , na.rm=TRUE),
    lns_corp_mdf_6352_sum   = sum(lns_corp_mdf_6352      , na.rm=TRUE),
    lns_corp_ins_6352_sum   = sum(lns_corp_ins_6352      , na.rm=TRUE),
    lns_corp_del_6352_sum   = sum(lns_corp_del_6352      , na.rm=TRUE),
    
    pro_minmaj_qual_sum        = paste(sort(pro_minmaj_qual, na.last=TRUE), collapse=", "),
    
    tsb_agc                = first(tsb_agc),
    
    ext_tsb_agc1_fst   = first(ext_tsb_agc1),
    ext_tsb_agc2_fst   = first(ext_tsb_agc2),
    ext_tsb_agc4_fst   = first(ext_tsb_agc4),
    
    ext_tsb_agc1_lst   = last(ext_tsb_agc1),
    ext_tsb_agc2_lst   = last(ext_tsb_agc2),
    ext_tsb_agc4_lst   = last(ext_tsb_agc4),
    
    ext_tsb_agc1_mn    = mean(ext_tsb_agc1 , na.rm=TRUE),
    ext_tsb_agc2_mn    = mean(ext_tsb_agc2 , na.rm=TRUE),
    ext_tsb_agc4_mn    = mean(ext_tsb_agc4,  na.rm=TRUE)
  )

isom$n_reforms[is.na(isom$t_date_fst)] <- 0
