desc <- 
rbind(
  list(name="t_id"             , from="texts", group="meta", description="Unique identifier of a SO version by including country shorthand, date, and version counter."),
  list(name="t_date"           , from="texts", group="meta", description="Date of the SO version - equals to (according to availibility) enactment, promulgation, acceptance."),
  list(name="t_dplus"          , from="texts", group="meta", description="Version counter that is zero under normal circumstances but might be higher if more than one version got enacted on the same date."),
  list(name="t_country"        , from="texts", group="meta", description="Country shorthand. In case of Swiss two seperate shorthands exist because there SO are spread among two bodies."),
  list(name="t_daccept"        , from="texts", group="meta", description="Date on which the SO were accepted, voted upon, decided upon, ... ."),
  list(name="t_dpromul"        , from="texts", group="meta", description="Date on which the SO were promulgated - made puplic, printed, published, ... ."),
  list(name="t_denact"         , from="texts", group="meta", description="Date on which the SO were enacted - came into force / took effect."),
  list(name="int_dupdate_texts", from="db", group="db", description="Date at which the 'texts' table of the database was last updated."),
  list(name="int_id_texts"     , from="db", group="db", description="Database internal enumeration of SO - this might change at any time. Do **not** use this as an id variable."),
  list(name="db_version"       , from="db", group="db", description="Version of the database which was used to create the data set. On every change the version number goes up by 0.01 - there is no distinction between major and minor version."),
  list(name="db_lastupdate"    , from="db", group="db", description="Date at which the database was last updated."),
  list(name="lns_all"          , from="textlines",              group="length", description="Number of lines - also known as sub paragraphs - within a particular SO."),
  list(name="wds_raw_all"      , from="textlines",              group="length", description="Number of words within a particular SO."),
  list(name="wds_clean_all"    , from="textlines",              group="length", description="Number of words within a particular SO after having striped away enumerations like, a), b), ..., 1., 2., ... I, II, ... and so forth."),
  list(name="lns_rel"          , from="textlines",              group="length", description="Number of lines that contain relevant content - e.g. no blank lines, no headlines, no appendices."),
  list(name="wds_raw_rel"      , from="textlines",              group="length", description="Number of words that are not from irrelevant lines - e.g. no blank lines, no headlines, no appendices."),
  list(name="wds_clean_rel"    , from="textlines",              group="length", description="Number of words that are not from irrelevant lines - e.g. no blank lines, no headlines, no appendices - after having striped away enumerations like, a), b), ..., 1., 2., ... I, II, ... and so forth."),
  list(name="lns_mdf"          , from="textlines",              group="change", description="Number of lines that were mofified - i.e. changed but not deleted or inserted."),
  list(name="wds_mdf"          , from="textlines",              group="change", description="Number of words modified - i.e. changed but not deleted or inserted."),
  list(name="pro_maj_mdf"      , from="textlines, linelinkage", group="minority/majority", description="Number of lines modified that were coded as majority friendly."),
  list(name="pro_min_mdf"      , from="textlines, linelinkage", group="minority/majority", description="Number of lines modified that were coded as minority friendly."),
  list(name="pro_non_mdf"      , from="textlines, linelinkage", group="minority/majority", description="Number of lines modified that were coded as neither majority nor minority friendly."),
  list(name="wds_pro_maj_mdf"  , from="textlines, linelinkage", group="minority/majority", description="Number of words modified that were coded as majority friendly."),
  list(name="wds_pro_min_mdf"  , from="textlines, linelinkage", group="minority/majority", description="Number of words modified that were coded as minority friendly."),
  list(name="wds_pro_non_mdf"  , from="textlines, linelinkage", group="minority/majority", description="Number of words modified that were coded as neither majority nor minority friendly."),
  list(name="wds_ins"          , from="textlines, linelinkage", group="change", description="Number of words that were inserted into SO."),
  list(name="lns_ins"          , from="textlines, linelinkage", group="change", description="Number of lines that were inserted into SO."),
  list(name="pro_maj_ins"      , from="textlines, linelinkage", group="minority/majority", description="Number of lines inserted that were coded as majority friendly."),
  list(name="pro_min_ins"      , from="textlines, linelinkage", group="minority/majority", description="Number of lines inserted that were coded as minority friendly."),
  list(name="pro_non_ins"      , from="textlines, linelinkage", group="minority/majority", description="Number of lines inserted that were coded as neither majority nor minority friendly."),
  list(name="wds_pro_maj_ins"  , from="textlines, linelinkage", group="minority/majority", description="Number of words inserted that were coded as majority friendly."),
  list(name="wds_pro_min_ins"  , from="textlines, linelinkage", group="minority/majority", description="Number of words inserted that were coded as minority friendly."),
  list(name="wds_pro_non_ins"  , from="textlines, linelinkage", group="minority/majority", description="Number of words inserted that were coded as neither majority nor minority friendly."),
  list(name="wds_del"          , from="textlines, linelinkage", group="change", description="Number of words that were deleted from old SO."),
  list(name="lns_del"          , from="textlines, linelinkage", group="change", description="Number of lines that were deleted from old SO."),
  list(name="pro_maj_del"      , from="textlines, linelinkage", group="minority/majority", description="Number of lines deleted that were coded as majority friendly."),
  list(name="pro_min_del"      , from="textlines, linelinkage", group="minority/majority", description="Number of lines deleted that were coded as minority friendly."),
  list(name="pro_non_del"      , from="textlines, linelinkage", group="minority/majority", description="Number of lines deleted that were coded as neither majority nor minority friendly."),
  list(name="wds_pro_maj_del"  , from="textlines, linelinkage", group="minority/majority", description="Number of words deleted that were coded as majority friendly."),
  list(name="wds_pro_min_del"  , from="textlines, linelinkage", group="minority/majority", description="Number of words deleted that were coded as minority friendly."),
  list(name="wds_pro_non_del"  , from="textlines, linelinkage", group="minority/majority", description="Number of words deleted that were coded as neither majority nor minority friendly."),
  list(name="pro_maj"          , from="linelinkage",            group="minority/majority", description="Number of lines coded as majority friendly."),
  list(name="pro_min"          , from="linelinkage",            group="minority/majority", description="Number of lines coded as minority friendly."),
  list(name="pro_non"          , from="linelinkage",            group="minority/majority", description="Number of lines coded as neither majority nor minority friendly."),
  list(name="wds_pro_maj"      , from="textlines, linelinkage", group="minority/majority", description="Number of words coded as majority friendly."),
  list(name="wds_pro_min"      , from="textlines, linelinkage", group="minority/majority", description="Number of words coded as minority friendly."),
  list(name="wds_pro_non"      , from="textlines, linelinkage", group="minority/majority", description="Number of words coded as neither majority nor minority friendly."),
  list(name="lns_chg"      , from="textlines, linelinkage", group="change", description="Number of lines that were changed from the old SO to the current - i.e. the sum of insertions, deletions and modifikations."),
  list(name="wds_chg"      , from="textlines, linelinkage", group="change", description="Number of words that were changed from the old SO to the current - i.e. the sum of insertions, deletions and modifikations."),
  list(name="lns_corp_8"       , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 8   "),
  list(name="lns_corp_9"       , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 9   "),
  list(name="lns_corp_10"      , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 10  "),
  list(name="lns_corp_21"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of lines with corpus code 21  "),
  list(name="lns_corp_22"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of lines with corpus code 22  "),
  list(name="lns_corp_23"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of lines with corpus code 23  "),
  list(name="lns_corp_25"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of lines with corpus code 25  "),
  list(name="lns_corp_26"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of lines with corpus code 26  "),
  list(name="lns_corp_27"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of lines with corpus code 27  "),
  list(name="lns_corp_28"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of lines with corpus code 28  "),
  list(name="lns_corp_29"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of lines with corpus code 29  "),
  list(name="lns_corp_31"      , from="textlines", group="raw corpus codes - 3 relationship to government ", description="Number of lines with corpus code 31  "),
  list(name="lns_corp_32"      , from="textlines", group="raw corpus codes - 3 relationship to government ", description="Number of lines with corpus code 32  "),
  list(name="lns_corp_33"      , from="textlines", group="raw corpus codes - 3 relationship to government ", description="Number of lines with corpus code 33  "),
  list(name="lns_corp_34"      , from="textlines", group="raw corpus codes - 3 relationship to government ", description="Number of lines with corpus code 34  "),
  list(name="lns_corp_43"      , from="textlines", group="raw corpus codes - 4 relationship to others", description="Number of lines with corpus code 43  "),
  list(name="lns_corp_45"      , from="textlines", group="raw corpus codes - 4 relationship to others", description="Number of lines with corpus code 45  "),
  list(name="lns_corp_51"      , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 51  "),
  list(name="lns_corp_52"      , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 52  "),
  list(name="lns_corp_53"      , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 53  "),
  list(name="lns_corp_54"      , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 54  "),
  list(name="lns_corp_55"      , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 55  "),
  list(name="lns_corp_56"      , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 56  "),
  list(name="lns_corp_66"      , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 66  "),
  list(name="lns_corp_67"      , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 67  "),
  list(name="lns_corp_68"      , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 68  "),
  list(name="lns_corp_71"      , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 71  "),
  list(name="lns_corp_72"      , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 72  "),
  list(name="lns_corp_73"      , from="textlines", group="raw corpus codes", description="Number of lines with corpus code 73  "),
  list(name="lns_corp_111"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 111 "),
  list(name="lns_corp_112"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 112 "),
  list(name="lns_corp_113"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 113 "),
  list(name="lns_corp_114"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 114 "),
  list(name="lns_corp_121"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 121 "),
  list(name="lns_corp_122"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 122 "),
  list(name="lns_corp_123"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 123 "),
  list(name="lns_corp_124"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 124 "),
  list(name="lns_corp_125"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 125 "),
  list(name="lns_corp_131"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 131 "),
  list(name="lns_corp_132"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 132 "),
  list(name="lns_corp_133"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 133 "),
  list(name="lns_corp_134"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 134 "),
  list(name="lns_corp_141"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 141 "),
  list(name="lns_corp_142"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 142 "),
  list(name="lns_corp_143"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 143 "),
  list(name="lns_corp_144"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 144 "),
  list(name="lns_corp_145"     , from="textlines", group="raw corpus codes - 1 law making", description="Number of lines with corpus code 145 "),
  list(name="lns_corp_241"     , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of lines with corpus code 241 "),
  list(name="lns_corp_242"     , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of lines with corpus code 242 "),
  list(name="lns_corp_243"     , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of lines with corpus code 243 "),
  list(name="lns_corp_244"     , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of lines with corpus code 244 "),
  list(name="lns_corp_411"     , from="textlines", group="raw corpus codes - 4 relationship to others", description="Number of lines with corpus code 411 "),
  list(name="lns_corp_412"     , from="textlines", group="raw corpus codes - 4 relationship to others", description="Number of lines with corpus code 412 "),
  list(name="lns_corp_421"     , from="textlines", group="raw corpus codes - 4 relationship to others", description="Number of lines with corpus code 421 "),
  list(name="lns_corp_422"     , from="textlines", group="raw corpus codes - 4 relationship to others", description="Number of lines with corpus code 422 "),
  list(name="lns_corp_441"     , from="textlines", group="raw corpus codes - 4 relationship to others", description="Number of lines with corpus code 441 "),
  list(name="lns_corp_442"     , from="textlines", group="raw corpus codes - 4 relationship to others", description="Number of lines with corpus code 442 "),
  list(name="lns_corp_611"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 611 "),
  list(name="lns_corp_612"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 612 "),
  list(name="lns_corp_613"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 613 "),
  list(name="lns_corp_631"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 631 "),
  list(name="lns_corp_632"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 632 "),
  list(name="lns_corp_633"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 633 "),
  list(name="lns_corp_634"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 634 "),
  list(name="lns_corp_636"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 636 "),
  list(name="lns_corp_637"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 637 "),
  list(name="lns_corp_638"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 638 "),
  list(name="lns_corp_639"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 639 "),
  list(name="lns_corp_641"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 641 "),
  list(name="lns_corp_642"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 642 "),
  list(name="lns_corp_643"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 643 "),
  list(name="lns_corp_651"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 651 "),
  list(name="lns_corp_652"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 652 "),
  list(name="lns_corp_653"     , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 653 "),
  list(name="lns_corp_999"     , from="textlines", group="raw corpus codes - 7-10 Misc", description="Number of lines with corpus code 999 "),
  list(name="lns_corp_6211"    , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 6211"),
  list(name="lns_corp_6212"    , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 6212"),
  list(name="lns_corp_6221"    , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 6221"),
  list(name="lns_corp_6222"    , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 6222"),
  list(name="lns_corp_6351"    , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 6351"),
  list(name="lns_corp_6352"    , from="textlines", group="raw corpus codes - 6 committees", description="Number of lines with corpus code 6352"),
  list(name="wds_corp_8"       , from="textlines", group="raw corpus codes - 7-10 Misc", description="Number of words with corpus code 8    - see lns_corp_8    for more information."),
  list(name="wds_corp_9"       , from="textlines", group="raw corpus codes - 7-10 Misc", description="Number of words with corpus code 9    - see lns_corp_9    for more information."),
  list(name="wds_corp_10"      , from="textlines", group="raw corpus codes - 7-10 Misc", description="Number of words with corpus code 10   - see lns_corp_10   for more information."),
  list(name="wds_corp_21"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of words with corpus code 21   - see lns_corp_21   for more information."),
  list(name="wds_corp_22"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of words with corpus code 22   - see lns_corp_22   for more information."),
  list(name="wds_corp_23"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of words with corpus code 23   - see lns_corp_23   for more information."),
  list(name="wds_corp_25"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of words with corpus code 25   - see lns_corp_25   for more information."),
  list(name="wds_corp_26"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of words with corpus code 26   - see lns_corp_26   for more information."),
  list(name="wds_corp_27"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of words with corpus code 27   - see lns_corp_27   for more information."),
  list(name="wds_corp_28"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of words with corpus code 28   - see lns_corp_28   for more information."),
  list(name="wds_corp_29"      , from="textlines", group="raw corpus codes - 2 special decision procedures", description="Number of words with corpus code 29   - see lns_corp_29   for more information."),
  list(name="wds_corp_31"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 31   - see lns_corp_31   for more information."),
  list(name="wds_corp_32"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 32   - see lns_corp_32   for more information."),
  list(name="wds_corp_33"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 33   - see lns_corp_33   for more information."),
  list(name="wds_corp_34"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 34   - see lns_corp_34   for more information."),
  list(name="wds_corp_43"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 43   - see lns_corp_43   for more information."),
  list(name="wds_corp_45"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 45   - see lns_corp_45   for more information."),
  list(name="wds_corp_51"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 51   - see lns_corp_51   for more information."),
  list(name="wds_corp_52"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 52   - see lns_corp_52   for more information."),
  list(name="wds_corp_53"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 53   - see lns_corp_53   for more information."),
  list(name="wds_corp_54"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 54   - see lns_corp_54   for more information."),
  list(name="wds_corp_55"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 55   - see lns_corp_55   for more information."),
  list(name="wds_corp_56"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 56   - see lns_corp_56   for more information."),
  list(name="wds_corp_66"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 66   - see lns_corp_66   for more information."),
  list(name="wds_corp_67"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 67   - see lns_corp_67   for more information."),
  list(name="wds_corp_68"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 68   - see lns_corp_68   for more information."),
  list(name="wds_corp_71"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 71   - see lns_corp_71   for more information."),
  list(name="wds_corp_72"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 72   - see lns_corp_72   for more information."),
  list(name="wds_corp_73"      , from="textlines", group="raw corpus codes", description="Number of words with corpus code 73   - see lns_corp_73   for more information."),
  list(name="wds_corp_111"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 111  - see lns_corp_111  for more information."),
  list(name="wds_corp_112"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 112  - see lns_corp_112  for more information."),
  list(name="wds_corp_113"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 113  - see lns_corp_113  for more information."),
  list(name="wds_corp_114"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 114  - see lns_corp_114  for more information."),
  list(name="wds_corp_121"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 121  - see lns_corp_121  for more information."),
  list(name="wds_corp_122"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 122  - see lns_corp_122  for more information."),
  list(name="wds_corp_123"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 123  - see lns_corp_123  for more information."),
  list(name="wds_corp_124"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 124  - see lns_corp_124  for more information."),
  list(name="wds_corp_125"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 125  - see lns_corp_125  for more information."),
  list(name="wds_corp_131"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 131  - see lns_corp_131  for more information."),
  list(name="wds_corp_132"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 132  - see lns_corp_132  for more information."),
  list(name="wds_corp_133"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 133  - see lns_corp_133  for more information."),
  list(name="wds_corp_134"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 134  - see lns_corp_134  for more information."),
  list(name="wds_corp_141"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 141  - see lns_corp_141  for more information."),
  list(name="wds_corp_142"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 142  - see lns_corp_142  for more information."),
  list(name="wds_corp_143"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 143  - see lns_corp_143  for more information."),
  list(name="wds_corp_144"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 144  - see lns_corp_144  for more information."),
  list(name="wds_corp_145"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 145  - see lns_corp_145  for more information."),
  list(name="wds_corp_241"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 241  - see lns_corp_241  for more information."),
  list(name="wds_corp_242"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 242  - see lns_corp_242  for more information."),
  list(name="wds_corp_243"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 243  - see lns_corp_243  for more information."),
  list(name="wds_corp_244"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 244  - see lns_corp_244  for more information."),
  list(name="wds_corp_411"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 411  - see lns_corp_411  for more information."),
  list(name="wds_corp_412"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 412  - see lns_corp_412  for more information."),
  list(name="wds_corp_421"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 421  - see lns_corp_421  for more information."),
  list(name="wds_corp_422"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 422  - see lns_corp_422  for more information."),
  list(name="wds_corp_441"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 441  - see lns_corp_441  for more information."),
  list(name="wds_corp_442"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 442  - see lns_corp_442  for more information."),
  list(name="wds_corp_611"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 611  - see lns_corp_611  for more information."),
  list(name="wds_corp_612"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 612  - see lns_corp_612  for more information."),
  list(name="wds_corp_613"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 613  - see lns_corp_613  for more information."),
  list(name="wds_corp_631"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 631  - see lns_corp_631  for more information."),
  list(name="wds_corp_632"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 632  - see lns_corp_632  for more information."),
  list(name="wds_corp_633"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 633  - see lns_corp_633  for more information."),
  list(name="wds_corp_634"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 634  - see lns_corp_634  for more information."),
  list(name="wds_corp_636"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 636  - see lns_corp_636  for more information."),
  list(name="wds_corp_637"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 637  - see lns_corp_637  for more information."),
  list(name="wds_corp_638"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 638  - see lns_corp_638  for more information."),
  list(name="wds_corp_639"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 639  - see lns_corp_639  for more information."),
  list(name="wds_corp_641"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 641  - see lns_corp_641  for more information."),
  list(name="wds_corp_642"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 642  - see lns_corp_642  for more information."),
  list(name="wds_corp_643"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 643  - see lns_corp_643  for more information."),
  list(name="wds_corp_651"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 651  - see lns_corp_651  for more information."),
  list(name="wds_corp_652"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 652  - see lns_corp_652  for more information."),
  list(name="wds_corp_653"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 653  - see lns_corp_653  for more information."),
  list(name="wds_corp_999"     , from="textlines", group="raw corpus codes", description="Number of words with corpus code 999  - see lns_corp_999  for more information."),
  list(name="wds_corp_6211"    , from="textlines", group="raw corpus codes", description="Number of words with corpus code 6211 - see lns_corp_6211 for more information."),
  list(name="wds_corp_6212"    , from="textlines", group="raw corpus codes", description="Number of words with corpus code 6212 - see lns_corp_6212 for more information."),
  list(name="wds_corp_6221"    , from="textlines", group="raw corpus codes", description="Number of words with corpus code 6221 - see lns_corp_6221 for more information."),
  list(name="wds_corp_6222"    , from="textlines", group="raw corpus codes", description="Number of words with corpus code 6222 - see lns_corp_6222 for more information."),
  list(name="wds_corp_6351"    , from="textlines", group="raw corpus codes", description="Number of words with corpus code 6351 - see lns_corp_6351 for more information."),
  list(name="wds_corp_6352"    , from="textlines", group="raw corpus codes", description="Number of words with corpus code 6352 - see lns_corp_6352 for more information."),
  list(name="lns_corp_agg_1"   , from="textlines", group="aggregated corpus codes", description="Number of lines with aggregated corpus code 1 - lawmaking."),
  list(name="lns_corp_agg_2"   , from="textlines", group="aggregated corpus codes", description="Number of lines with aggregated corpus code 2 - special decission rules."),
  list(name="lns_corp_agg_3"   , from="textlines", group="aggregated corpus codes", description="Number of lines with aggregated corpus code 3 - elections."),
  list(name="lns_corp_agg_4"   , from="textlines", group="aggregated corpus codes", description="Number of lines with aggregated corpus code 4 - government control."),
  list(name="lns_corp_agg_5"   , from="textlines", group="aggregated corpus codes", description="Number of lines with aggregated corpus code 5 - puplicity"),
  list(name="lns_corp_agg_6"   , from="textlines", group="aggregated corpus codes", description="Number of lines with aggregated corpus code 6 - not relevant"),
  list(name="lns_corp_agg_7"   , from="textlines", group="aggregated corpus codes", description="Number of lines with aggregated corpus code 7 - not applicaple"),
  list(name="wds_corp_agg_1"   , from="textlines", group="aggregated corpus codes", description="Number of words with aggregated corpus code 1 - lawmaking."),
  list(name="wds_corp_agg_2"   , from="textlines", group="aggregated corpus codes", description="Number of words with aggregated corpus code 2 - special decission rules."),
  list(name="wds_corp_agg_3"   , from="textlines", group="aggregated corpus codes", description="Number of words with aggregated corpus code 3 - elections."),
  list(name="wds_corp_agg_4"   , from="textlines", group="aggregated corpus codes", description="Number of words with aggregated corpus code 4 - government control."),
  list(name="wds_corp_agg_5"   , from="textlines", group="aggregated corpus codes", description="Number of words with aggregated corpus code 5 - puplicity"),
  list(name="wds_corp_agg_6"   , from="textlines", group="aggregated corpus codes", description="Number of words with aggregated corpus code 6 - not relevant"),
  list(name="wds_corp_agg_7"   , from="textlines", group="aggregated corpus codes", description="Number of words with aggregated corpus code 7 - not applicaple")
)
desc <- as.data.frame(desc)
description <- 
  data_frame(
    name  = unlist(desc$name),
    from  = unlist(desc$from),
    group = unlist(desc$group), 
    desc  = unlist(desc$description)
  )





















